---
title: "Filtering_Data"
output: html_document
date: "2026-02-25"
---

Loading packages
```{r}
library(tidyverse) #cleaning data easily
library(here) #reference file locations
library(dplyr) # cleaning data easily
library(boxr) #accessing box files, aka data without downloading
set.seed(123)
```

Filtering the mosq data further
```{r}
#loading the data
mosq_data <- read.csv(here("Data/mosquito_data.csv")) #619644

#want to keep c. quinquefasciatus, c. tarsalis, aedes aegypti
mosq_species<- filter(mosq_data, mosq_data$Species == "Culex quinquefasciatus" | mosq_data$Species == "Culex tarsalis" | mosq_data$Species == "Aedes aegypti") # observations 619644

mosq_species %>% count(Species) #confirming species


#trimming data to lat(33.7987, 33.2043), lon( -112.573997704,   -111.5837)
mosq_geo<- filter(mosq_species, mosq_species$Latitude >= 33.2043 &  33.7987 >= mosq_species$Latitude, mosq_species$Longitude >= -112.573997704 &  -111.5837 >=mosq_species$Longitude ) #86482 species





mosq_geo$Date <- as.Date(mosq_geo$Date)
mosq_geo$Week <- format(mosq_geo$Date, "%Y-%U")


#need add week

mosq_keep <- as.Date(mosq_keep$Date)
mosq_keep$Week <- format(mosq_keep$Date, "%U")

#confirming points on graph
lat_lon<- mosq_keep[c("Latitude", "Longitude")]
plot(lat_lon) #testing on graph

summary(mosq_keep) #looking at filter data frame!

write.csv(mosq_keep, here("Natalie/data_cleaned/mosq_keep.csv"))
write.csv(lat_lon, here("Natalie/data_cleaned/lat_lon.csv"))

```

Dealing with Climate Data - May need help with this??? 
**Using Desiree Cliamte data right? what it called....**
**NDVI, Occuarnce, Desiree Climate Data?**
**need help figuring out how to access data **
```{r}
box_auth()
```





