---
title: "SDM_Calculation"
output: html_document
date: "2026-03-01"
---

Loading Packages
```{r}
library(adehabitatHS) #PCA, page 161, ENFA
library(dplyr) #Data management
library(ggplot2) #graphinh
library(gstat) #geostat
library(here) # to use here directory to open data files easier
library(PresenceAbsence)
library(pROC) #ENFA
library(randomForest) #RF Model
library(raster) #Raster working
library(tidyverse) #Data management
library(terra) #SDM Package

set.seed(123)
```


Loading in Data 
```{r}

cq <- read.csv(here("Natalie/data_cleaned/cq_df.csv"))
ct <- read.csv(here("Natalie/data_cleaned/ct_df.csv"))
aa<- read.csv(here("Natalie/data_cleaned/aa_df.csv"))

```

Test and train Data frames
```{r}
#splitting into training data --> cq
train_indices_cq <- sample(1:nrow(cq), size = 0.8 *nrow(cq)) #taking a random sample from cq
train_data_cq <- cq[train_indices_cq,]
test_data_cq <- cq[-train_indices_cq,]
nrow(train_data_cq) 
nrow(test_data_cq) 

#write.csv(train_data_cq, file = here("Natalie/data_cleaned/test_train/train_data_cq.csv"))
#write.csv(test_data_cq, file = here("Natalie/data_cleaned/test_train/test_data_cq.csv"))



# Ct
train_indices_ct <- sample(1:nrow(ct), size = 0.8 *nrow(ct)) #taking a random sample from ct
train_data_ct <- ct[train_indices_ct,]
test_data_ct <- ct[-train_indices_ct,]
nrow(train_data_ct) 
nrow(test_data_ct) 

#write.csv(train_data_ct, file = here("Natalie/data_cleaned/test_train/train_data_ct.csv"))
#write.csv(test_data_ct, file = here("Natalie/data_cleaned/test_train/test_data_ct.csv"))



#aa
train_indices_aa <- sample(1:nrow(aa), size = 0.8 *nrow(aa)) #taking a random sample from aa
train_data_aa <- aa[train_indices_aa,]
test_data_aa <- aa[-train_indices_aa,]
nrow(train_data_aa) 
nrow(test_data_aa) 

#write.csv(train_data_aa, file = here("Natalie/data_cleaned/test_train/train_data_aa.csv"))
#write.csv(test_data_aa, file = here("Natalie/data_cleaned/test_train/test_data_aa.csv"))
```


GLM - cq
```{r}
glm_model_cq_h20 <- glm(cq ~ 
                        NDVI+ MNDWI + prec1 + prec2 + tmin1 + tavg1 + tmax1 + humd2, 
                        data = train_data_cq, family = binomial(link = "logit"))


#saveRDS(glm_model_cq_h20, file = here("Natalie/data_cleaned/models/glm_model_cq_h20.rds"))


glm_model_cq <- glm(cq ~ prec1 + prec2 + tmin1 + tavg1 + tmax1 + humd2, 
                    data = train_data_cq, family = binomial(link = "logit"))

#saveRDS(glm_model_cq, file = here("Natalie/data_cleaned/models/glm_model_cq.rds"))
```


GLM ct
```{r}
glm_model_ct_h20 <- glm(ct ~ 
                        NDVI+ MNDWI+ prec1 + prec2 + tmin1 + tavg1+ tmax1+ humd2, 
                        data = train_data_ct, family = binomial(link = "logit"))

glm_model_ct<- glm(ct ~ 
                        prec1 + prec2 + tmin1 + tavg1+ tmax1+ humd2, 
                        data = train_data_ct,, family = binomial(link = "logit"))


#saveRDS(glm_model_ct_h20, file = here("Natalie/data_cleaned/models/glm_model_ct_h20.rds"))
#saveRDS(glm_model_ct, file = here("Natalie/data_cleaned/models/glm_model_ct.rds"))


```


GLM aa
```{r}
glm_model_aa_h20 <- glm(aa~ 
                          NDVI+ MNDWI+ prec1+ prec2+ tmin2+ tavg2+ humd2+ tmax2, 
                          data = train_data_aa, family = binomial(link = "logit"))

glm_model_aa <- glm(aa ~ 
                      prec1+ prec2+ tmin2+ tavg2+ humd2+ tmax2, 
                      data = train_data_aa, family = binomial(link = "logit"))

#saveRDS(glm_model_aa_h20, file = here("Natalie/data_cleaned/models/glm_model_aa_h20.rds"))
#saveRDS(glm_model_aa, file = here("Natalie/data_cleaned/models/glm_model_aa.rds"))

```


RF-cq
```{r}

rf_model_cq_h2o <- randomForest(x = train_data_cq[, c("NDVI", "MNDWI", "prec1", "prec2", "tmin1", 
                                                      "tavg1", "tmax1", "humd2")],
                                 y=as.factor(train_data_cq$cq), nodesize = 10, ntree = 100)

rf_model_cq <- randomForest(x = train_data_cq[, c("prec1", "prec2", "tmin1", "tavg1", 
                                                    "tmax1", "humd2")],
                                 y=as.factor(train_data_cq$cq), nodesize = 10, ntree = 100)

#saveRDS(rf_model_cq_h2o, file = here("Natalie/data_cleaned/models/rf_model_cq_h2o.rds"))
#saveRDS(rf_model_cq, file = here("Natalie/data_cleaned/models/rf_model_cq.rds"))


```


RF -ct
```{r}
rf_model_ct_h2o <- randomForest(x = train_data_ct[, c( "NDVI", "MNDWI", "prec1", "prec2", "tmin1", 
                                                       "tavg1","tmax1", "humd2")], 
                                y=as.factor(train_data_ct$ct), nodesize = 10, ntree = 100)

rf_model_ct <- randomForest(x = train_data_ct[, c("prec1", "prec2", "tmin1", 
                                                       "tavg1","tmax1", "humd2")], 
                                y=as.factor(train_data_ct$ct), nodesize = 10, ntree = 100)

#saveRDS(rf_model_ct_h2o, file = here("Natalie/data_cleaned/models/rf_model_ct_h2o.rds"))
#saveRDS(rf_model_ct, file = here("Natalie/data_cleaned/models/rf_model_ct.rds"))

```


RF - aa
```{r}
rf_model_aa_h2o <- randomForest(x = train_data_aa[, c("NDVI", "MNDWI", "prec1", "prec2", "tmin2", 
                                                      "tavg2","humd2", "tmax2")],  
                                  y=as.factor(train_data_aa$aa), nodesize = 10, ntree = 100)

rf_model_aa <- randomForest(x = train_data_aa[, c("prec1", "prec2", "tmin2","tavg2","humd2", 
                                                  "tmax2")], 
                                      y=as.factor(train_data_aa$aa), nodesize = 10, ntree = 100)

#saveRDS(rf_model_aa_h2o, file = here("Natalie/data_cleaned/models/rf_model_aa_h2o.rds"))
#saveRDS(rf_model_aa, file = here("Natalie/data_cleaned/models/rf_model_aa.rds"))

```


ENFA - cq
```{r}
pc_cq_h2o <- dudi.pca(train_data_cq[, c("NDVI", "MNDWI", "prec1", "prec2", "tmin1", 
                                        "tavg1", "tmax1", "humd2")], 
                                      scannf = FALSE, nf =2)
ENFA_cq_h2o <- enfa(pc_cq_h2o, train_data_cq$cq, scan = FALSE)





pc_cq <- dudi.pca(train_data_cq[, c("prec1", "prec2", "tmin1", "tavg1", "tmax1", "humd2")], 
                                      scannf = FALSE, nf =2)
ENFA_cq <- enfa(pc_cq, train_data_cq$cq, scan = FALSE)

#saveRDS(ENFA_cq_h2o, file = here("Natalie/data_cleaned/models/ENFA_cq_h2o.rds"))
#saveRDS(ENFA_cq, file = here("Natalie/data_cleaned/models/ENFA_cq.rds"))

```



ENFA - ct
```{r}

pc_ct_h2o <- dudi.pca(train_data_ct[, c("NDVI", "MNDWI", "prec1", "prec2", "tmin1", 
                                                       "tavg1","tmax1", "humd2")], 
                                      scannf = FALSE, nf =2)
ENFA_ct_h2o <- enfa(pc_ct_h2o, train_data_ct$ct, scan = FALSE)


pc_ct <- dudi.pca(train_data_ct[, c("prec1", "prec2", "tmin1","tavg1","tmax1", "humd2")], 
                                      scannf = FALSE, nf =2)
ENFA_ct <- enfa(pc_ct, train_data_ct$ct, scan = FALSE)

#saveRDS(ENFA_ct_h2o, file = here("Natalie/data_cleaned/models/ENFA_ct_h2o.rds"))
#saveRDS(ENFA_ct, file = here("Natalie/data_cleaned/models/ENFA_ct.rds"))

```



ENFA - aa
```{r}

pc_aa_h2o <- dudi.pca(train_data_aa[, c("NDVI", "MNDWI", "prec1", "prec2", "tmin2", 
                                                      "tavg2","humd2", "tmax2")], 
                                      scannf = FALSE, nf =2)
ENFA_aa_h2o <- enfa(pc_aa_h2o, train_data_aa$aa, scan = FALSE)


pc_aa <- dudi.pca(train_data_aa[, c("prec1", "prec2", "tmin2", "tavg2","humd2", "tmax2")], 
                                      scannf = FALSE, nf =2)
ENFA_aa <- enfa(pc_aa, train_data_aa$aa, scan = FALSE)

#saveRDS(ENFA_aa_h2o, file = here("Natalie/data_cleaned/models/ENFA_aa_h2o.rds"))
#saveRDS(ENFA_aa, file = here("Natalie/data_cleaned/models/ENFA_aa.rds"))

```


Loading in Weather Tiffs
```{r}
maricopa <- extent(-112.573997704, -111.5837, 33.2043, 33.7987)

#NDVI <- rast("/Users/nooni/Box/RNR597_data/data/NDVI.tif")
#MNDWI <-rast("/Users/nooni/Box/RNR597_data/data/MNDWI.tif")

#YW201319
humd1_yw201319<-rast("/Users/nooni/Box/RNR597_data/data/yw201319/humd1.tif")
humd2_yw201319<-rast("/Users/nooni/Box/RNR597_data/data/yw201319/humd2.tif")
prec1_yw201319<-rast("/Users/nooni/Box/RNR597_data/data/yw201319/prec1.tif")
prec2_yw201319<-rast("/Users/nooni/Box/RNR597_data/data/yw201319/prec2.tif")
tavg1_yw201319<-rast("/Users/nooni/Box/RNR597_data/data/yw201319/tavg1.tif")
tavg2_yw201319<-rast("/Users/nooni/Box/RNR597_data/data/yw201319/tavg2.tif")
tmax1_yw201319<-rast("/Users/nooni/Box/RNR597_data/data/yw201319/tmax1.tif")
tmax2_yw201319<-rast("/Users/nooni/Box/RNR597_data/data/yw201319/tmax2.tif")
tmin1_yw201319<-rast("/Users/nooni/Box/RNR597_data/data/yw201319/tmin1.tif")
tmin2_yw201319<-rast("/Users/nooni/Box/RNR597_data/data/yw201319/tmin2.tif")

#making one raster for this year
YW201319_list <-c(humd1_yw201319, humd2_yw201319, prec1_yw201319, prec2_yw201319, tavg1_yw201319,tavg2_yw201319,tmax1_yw201319, tmax2_yw201319, tmin1_yw201319,tmin2_yw201319, NDVI, MNDWI)
YW201319_rast <-stack(YW201319_list)

YW201319_rast <- crop(YW201319_rast, maricopa)
#plot(YW201319_rast)
#writeRaster(YW201319_rast, here("Natalie/data_cleaned/Env_raster/YW201319_rast.tif"), overwrite = TRUE)

#YW201332
humd1_yw201332<-rast("/Users/nooni/Box/RNR597_data/data/yw201332/humd1.tif")
humd2_yw201332<-rast("/Users/nooni/Box/RNR597_data/data/yw201332/humd2.tif")
prec1_yw201332<-rast("/Users/nooni/Box/RNR597_data/data/yw201332/prec1.tif")
prec2_yw201332<-rast("/Users/nooni/Box/RNR597_data/data/yw201332/prec2.tif")
tavg1_yw201332<-rast("/Users/nooni/Box/RNR597_data/data/yw201332/tavg1.tif")
tavg2_yw201332<-rast("/Users/nooni/Box/RNR597_data/data/yw201332/tavg2.tif")
tmax1_yw201332<-rast("/Users/nooni/Box/RNR597_data/data/yw201332/tmax1.tif")
tmax2_yw201332<-rast("/Users/nooni/Box/RNR597_data/data/yw201332/tmax2.tif")
tmin1_yw201332<-rast("/Users/nooni/Box/RNR597_data/data/yw201332/tmin1.tif")
tmin2_yw201332<-rast("/Users/nooni/Box/RNR597_data/data/yw201332/tmin2.tif")


#making one raster for this year
yw201332_list <-c(humd1_yw201332, humd2_yw201332, prec1_yw201332, prec2_yw201332, tavg1_yw201332,tavg2_yw201332,tmax1_yw201332, tmax2_yw201332, tmin1_yw201332,tmin2_yw201332, NDVI, MNDWI)
yw201332_rast <-stack(yw201332_list)

yw201332_rast <- crop(yw201332_rast, maricopa)
#plot(YW201332_rast)
writeRaster(yw201332_rast, here("Natalie/data_cleaned/Env_raster/YW201332_rast.tiff"), overwrite = TRUE)


#YW201345
humd1_yw201345<-rast("/Users/nooni/Box/RNR597_data/data/yw201345/humd1.tif")
humd2_yw201345<-rast("/Users/nooni/Box/RNR597_data/data/yw201345/humd2.tif")
prec1_yw201345<-rast("/Users/nooni/Box/RNR597_data/data/yw201345/prec1.tif")
prec2_yw201345<-rast("/Users/nooni/Box/RNR597_data/data/yw201345/prec2.tif")
tavg1_yw201345<-rast("/Users/nooni/Box/RNR597_data/data/yw201345/tavg1.tif")
tavg2_yw201345<-rast("/Users/nooni/Box/RNR597_data/data/yw201345/tavg2.tif")
tmax1_yw201345<-rast("/Users/nooni/Box/RNR597_data/data/yw201345/tmax1.tif")
tmax2_yw201345<-rast("/Users/nooni/Box/RNR597_data/data/yw201345/tmax2.tif")
tmin1_yw201345<-rast("/Users/nooni/Box/RNR597_data/data/yw201345/tmin1.tif")
tmin2_yw201345<-rast("/Users/nooni/Box/RNR597_data/data/yw201345/tmin2.tif")

#making one raster for this year
yw201345_list <-c(humd1_yw201345, humd2_yw201345, prec1_yw201345, prec2_yw201345, tavg1_yw201345,tavg2_yw201345,tmax1_yw201345, tmax2_yw201345, tmin1_yw201345,tmin2_yw201345, NDVI, MNDWI)
yw201345_rast <-stack(yw201345_list)

yw201345_rast <- crop(yw201345_rast, maricopa)
#plot(YW201345_rast)
#writeRaster(yw201345_rast, here("Natalie/data_cleaned/Env_raster/YW201345_rast.tiff"), overwrite = TRUE)


#YW201719
humd1_yw201719<-rast("/Users/nooni/Box/RNR597_data/data/yw201719/humd1.tif")
humd2_yw201719<-rast("/Users/nooni/Box/RNR597_data/data/yw201719/humd2.tif")
prec1_yw201719<-rast("/Users/nooni/Box/RNR597_data/data/yw201719/prec1.tif")
prec2_yw201719<-rast("/Users/nooni/Box/RNR597_data/data/yw201719/prec2.tif")
tavg1_yw201719<-rast("/Users/nooni/Box/RNR597_data/data/yw201719/tavg1.tif")
tavg2_yw201719<-rast("/Users/nooni/Box/RNR597_data/data/yw201719/tavg2.tif")
tmax1_yw201719<-rast("/Users/nooni/Box/RNR597_data/data/yw201719/tmax1.tif")
tmax2_yw201719<-rast("/Users/nooni/Box/RNR597_data/data/yw201719/tmax2.tif")
tmin1_yw201719<-rast("/Users/nooni/Box/RNR597_data/data/yw201719/tmin1.tif")
tmin2_yw201719<-rast("/Users/nooni/Box/RNR597_data/data/yw201719/tmin2.tif")


#making one raster for this year
yw201719_list <-c(humd1_yw201719, humd2_yw201719, prec1_yw201719, prec2_yw201719, tavg1_yw201719,tavg2_yw201719,tmax1_yw201719, tmax2_yw201719, tmin1_yw201719,tmin2_yw201719, NDVI, MNDWI)
yw201719_rast <-stack(yw201719_list)

yw201719_rast <- crop(yw201719_rast, maricopa)
#plot(YW201719_rast)
#writeRaster(yw201719_rast, here("Natalie/data_cleaned/Env_raster/YW201719_rast.tiff"), overwrite = TRUE)


#YW201732
humd1_yw201732<-rast("/Users/nooni/Box/RNR597_data/data/yw201732/humd1.tif")
humd2_yw201732<-rast("/Users/nooni/Box/RNR597_data/data/yw201732/humd2.tif")
prec1_yw201732<-rast("/Users/nooni/Box/RNR597_data/data/yw201732/prec1.tif")
prec2_yw201732<-rast("/Users/nooni/Box/RNR597_data/data/yw201732/prec2.tif")
tavg1_yw201732<-rast("/Users/nooni/Box/RNR597_data/data/yw201732/tavg1.tif")
tavg2_yw201732<-rast("/Users/nooni/Box/RNR597_data/data/yw201732/tavg2.tif")
tmax1_yw201732<-rast("/Users/nooni/Box/RNR597_data/data/yw201732/tmax1.tif")
tmax2_yw201732<-rast("/Users/nooni/Box/RNR597_data/data/yw201732/tmax2.tif")
tmin1_yw201732<-rast("/Users/nooni/Box/RNR597_data/data/yw201732/tmin1.tif")
tmin2_yw201732<-rast("/Users/nooni/Box/RNR597_data/data/yw201732/tmin2.tif")

#making one raster for this year
yw201732_list <-c(humd1_yw201732, humd2_yw201732, prec1_yw201732, prec2_yw201732, tavg1_yw201732,tavg2_yw201732,tmax1_yw201732, tmax2_yw201732, tmin1_yw201732,tmin2_yw201732, NDVI, MNDWI)
yw201732_rast <-stack(yw201732_list)

yw201732_rast <- crop(yw201732_rast, maricopa)
#plot(YW201732_rast)
#writeRaster(yw201732_rast, here("Natalie/data_cleaned/Env_raster/YW201732_rast.tiff"), overwrite = TRUE)


#YW201745
humd1_yw201745<-rast("/Users/nooni/Box/RNR597_data/data/yw201745/humd1.tif")
humd2_yw201745<-rast("/Users/nooni/Box/RNR597_data/data/yw201745/humd2.tif")
prec1_yw201745<-rast("/Users/nooni/Box/RNR597_data/data/yw201745/prec1.tif")
prec2_yw201745<-rast("/Users/nooni/Box/RNR597_data/data/yw201745/prec2.tif")
tavg1_yw201745<-rast("/Users/nooni/Box/RNR597_data/data/yw201745/tavg1.tif")
tavg2_yw201745<-rast("/Users/nooni/Box/RNR597_data/data/yw201745/tavg2.tif")
tmax1_yw201745<-rast("/Users/nooni/Box/RNR597_data/data/yw201745/tmax1.tif")
tmax2_yw201745<-rast("/Users/nooni/Box/RNR597_data/data/yw201745/tmax2.tif")
tmin1_yw201745<-rast("/Users/nooni/Box/RNR597_data/data/yw201745/tmin1.tif")
tmin2_yw201745<-rast("/Users/nooni/Box/RNR597_data/data/yw201745/tmin2.tif")

#making one raster for this year
yw201745_list <-c(humd1_yw201745, humd2_yw201745, prec1_yw201745, prec2_yw201745, tavg1_yw201745,tavg2_yw201745,tmax1_yw201745, tmax2_yw201745, tmin1_yw201745,tmin2_yw201745, NDVI, MNDWI)
yw201745_rast <-stack(yw201745_list)

yw201745_rast <- crop(yw201745_rast, maricopa)
#plot(YW201745_rast)
#writeRaster(yw201745_rast, here("Natalie/data_cleaned/Env_raster/YW201745_rast.tiff"), overwrite = TRUE)


#YW202119
humd1_yw202119<-rast("/Users/nooni/Box/RNR597_data/data/yw202119/humd1.tif")
humd2_yw202119<-rast("/Users/nooni/Box/RNR597_data/data/yw202119/humd2.tif")
prec1_yw202119<-rast("/Users/nooni/Box/RNR597_data/data/yw202119/prec1.tif")
prec2_yw202119<-rast("/Users/nooni/Box/RNR597_data/data/yw202119/prec2.tif")
tavg1_yw202119<-rast("/Users/nooni/Box/RNR597_data/data/yw202119/tavg1.tif")
tavg2_yw202119<-rast("/Users/nooni/Box/RNR597_data/data/yw202119/tavg2.tif")
tmax1_yw202119<-rast("/Users/nooni/Box/RNR597_data/data/yw202119/tmax1.tif")
tmax2_yw202119<-rast("/Users/nooni/Box/RNR597_data/data/yw202119/tmax2.tif")
tmin1_yw202119<-rast("/Users/nooni/Box/RNR597_data/data/yw202119/tmin1.tif")
tmin2_yw202119<-rast("/Users/nooni/Box/RNR597_data/data/yw202119/tmin2.tif")

#making one raster for this year
yw202119_list <-c(humd1_yw202119, humd2_yw202119, prec1_yw202119, prec2_yw202119, tavg1_yw202119,tavg2_yw202119,tmax1_yw202119, tmax2_yw202119, tmin1_yw202119,tmin2_yw202119, NDVI, MNDWI)
yw202119_rast <-stack(yw202119_list)

yw202119_rast <- crop(yw202119_rast, maricopa)
#plot(YW202119_rast)
#writeRaster(yw202119_rast, here("Natalie/data_cleaned/Env_raster/YW202119_rast.tiff"), overwrite = TRUE)



#YW202132
humd1_yw202132<-rast("/Users/nooni/Box/RNR597_data/data/yw202132/humd1.tif")
humd2_yw202132<-rast("/Users/nooni/Box/RNR597_data/data/yw202132/humd2.tif")
prec1_yw202132<-rast("/Users/nooni/Box/RNR597_data/data/yw202132/prec1.tif")
prec2_yw202132<-rast("/Users/nooni/Box/RNR597_data/data/yw202132/prec2.tif")
tavg1_yw202132<-rast("/Users/nooni/Box/RNR597_data/data/yw202132/tavg1.tif")
tavg2_yw202132<-rast("/Users/nooni/Box/RNR597_data/data/yw202132/tavg2.tif")
tmax1_yw202132<-rast("/Users/nooni/Box/RNR597_data/data/yw202132/tmax1.tif")
tmax2_yw202132<-rast("/Users/nooni/Box/RNR597_data/data/yw202132/tmax2.tif")
tmin1_yw202132<-rast("/Users/nooni/Box/RNR597_data/data/yw202132/tmin1.tif")
tmin2_yw202132<-rast("/Users/nooni/Box/RNR597_data/data/yw202132/tmin2.tif")

#making one raster for this year
yw202132_list <-c(humd1_yw202132, humd2_yw202132, prec1_yw202132, prec2_yw202132, tavg1_yw202132,tavg2_yw202132,tmax1_yw202132, tmax2_yw202132, tmin1_yw202132,tmin2_yw202132, NDVI, MNDWI)
yw202132_rast <-stack(yw202132_list)

yw202132_rast <- crop(yw202132_rast, maricopa)
#plot(YW202132_rast)
#writeRaster(yw202132_rast, here("Natalie/data_cleaned/Env_raster/YW202132_rast.tiff"), overwrite = TRUE)


#YW202145
humd1_yw202145<-rast("/Users/nooni/Box/RNR597_data/data/yw202145/humd1.tif")
humd2_yw202145<-rast("/Users/nooni/Box/RNR597_data/data/yw202145/humd2.tif")
prec1_yw202145<-rast("/Users/nooni/Box/RNR597_data/data/yw202145/prec1.tif")
prec2_yw202145<-rast("/Users/nooni/Box/RNR597_data/data/yw202145/prec2.tif")
tavg1_yw202145<-rast("/Users/nooni/Box/RNR597_data/data/yw202145/tavg1.tif")
tavg2_yw202145<-rast("/Users/nooni/Box/RNR597_data/data/yw202145/tavg2.tif")
tmax1_yw202145<-rast("/Users/nooni/Box/RNR597_data/data/yw202145/tmax1.tif")
tmax2_yw202145<-rast("/Users/nooni/Box/RNR597_data/data/yw202145/tmax2.tif")
tmin1_yw202145<-rast("/Users/nooni/Box/RNR597_data/data/yw202145/tmin1.tif")
tmin2_yw202145<-rast("/Users/nooni/Box/RNR597_data/data/yw202145/tmin2.tif")

#Making year raster
yw202145_list <-c(humd1_yw202145, humd2_yw202145, prec1_yw202145, prec2_yw202145, tavg1_yw202145,tavg2_yw202145,tmax1_yw202145, tmax2_yw202145, tmin1_yw202145,tmin2_yw202145, NDVI, MNDWI)
yw202145_rast <-stack(yw202145_list)

yw202145_rast <- crop(yw202145_rast, maricopa)
#plot(YW202145_rast)
#writeRaster(yw202145_rast, here("Natalie/data_cleaned/Env_raster/YW202145_rast.tiff"), overwrite = TRUE)
```


cq-predict
```{r}
cq_subset <- c("humd2", "prec1", "prec2", "tavg1","tmax1", "tmin1")
cq_subset_h2o <- c("humd2", "prec1", "prec2", "tavg1","tmax1", "tmin1", "NDVI", "MNDWI")

#Subsetting years
yw201319_cq <- subset(YW201319_rast, cq_subset)
yw201319_cq_h2o <- subset(YW201319_rast, cq_subset_h2o)
yw201332_cq <-subset(yw201332_rast, cq_subset)
yw201332_cq_h2o <- subset(yw201332_rast, cq_subset_h2o)
yw201345_cq <-subset(yw201345_rast, cq_subset)
yw201345_cq_h2o<-subset(yw201345_rast, cq_subset_h2o)
yw201719_cq<-subset(yw201719_rast, cq_subset)
yw201719_cq_h2o <-subset(yw201719_rast, cq_subset_h2o)
yw201732_cq<-subset(yw201732_rast, cq_subset)
yw201732_cq_h2o <-subset(yw201732_rast, cq_subset_h2o)
yw201745_cq<-subset(yw201745_rast, cq_subset)
yw201745_cq_h2o <-subset(yw201745_rast, cq_subset_h2o)
yw202119_cq<-subset(yw202119_rast, cq_subset)
yw202119_cq_h2o <-subset(yw202119_rast, cq_subset_h2o)
yw202132_cq<-subset(yw202132_rast, cq_subset)
yw202132_cq_h2o <-subset(yw202132_rast, cq_subset_h2o)
yw202145_cq<-subset(yw202145_rast, cq_subset)
yw202145_cq_h2o <- subset(yw202145_rast, cq_subset_h2o)


#**GLM**
#glm_model_cq_h20 <- readRDS(here("Natalie/data_cleaned/models/glm_model_cq_h20.rds"))
#glm_model_cq <- readRDS(here("Natalie/data_cleaned/models/glm_model_cq.rds"))

cq201319_glm <- predict(yw201319_cq, glm_model_cq) #without water
cq201319_h2o_glm <- predict(yw201319_cq_h2o, glm_model_cq_h20) #with water

cq201332_glm <- predict(yw201332_cq, glm_model_cq) #without water
cq201332_h2o_glm <- predict(yw201332_cq_h2o, glm_model_cq_h20) #with water

cq201345_glm <- predict(yw201345_cq, glm_model_cq) #without water
cq201345_h2o_glm <- predict(yw201345_cq_h2o, glm_model_cq_h20) #with water

cq201919_glm <- predict(yw201719_cq, glm_model_cq) #without water
cq201919_h2o_glm <- predict(yw201719_cq_h2o, glm_model_cq_h20) #with water

cq201932_glm <- predict(yw201732_cq, glm_model_cq) #without water
cq201932_h2o_glm <- predict(yw201732_cq_h2o, glm_model_cq_h20) #with water

cq201945_glm <- predict(yw201745_cq, glm_model_cq) #without water
cq201945_h2o_glm <- predict(yw201745_cq_h2o, glm_model_cq_h20) #with water

cq202119_glm <- predict(yw202119_cq, glm_model_cq) #without water
cq202119_h2o_glm <- predict(yw202119_cq_h2o, glm_model_cq_h20) #with water

cq202132_glm <- predict(yw202132_cq, glm_model_cq) #without water
cq202132_h2o_glm <- predict(yw202132_cq_h2o, glm_model_cq_h20) #with water


cq202145_glm <- predict(yw202145_cq, glm_model_cq) #without water
cq202145_h2o_glm <- predict(yw202145_cq_h2o, glm_model_cq_h20) #with water


#writeRaster(cq201319_glm, file = "/Users/nooni/Box/RNR597_data/prediction/cq201319_glm.tif")
#writeRaster(cq201319_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/cq201319_h2o_glm.tif")
#writeRaster(cq201332_glm, file = "/Users/nooni/Box/RNR597_data/prediction/cq201332_glm.tif")
#writeRaster(cq201332_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/cq201332_h2o_glm.tif")
#writeRaster(cq201345_glm, file = "/Users/nooni/Box/RNR597_data/prediction/cq201345_glm.tif")
#writeRaster(cq201345_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/cq201345_h2o_glm.tif")
#writeRaster(cq201919_glm, file = "/Users/nooni/Box/RNR597_data/prediction/cq201919_glm.tif")
#writeRaster(cq201345_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/cq201919_h2o_glm.tif")
#writeRaster(cq201919_glm, file = "/Users/nooni/Box/RNR597_data/prediction/cq201932_glm.tif")
#writeRaster(cq201932_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/cq201932_h2o_glm.tif")
#writeRaster(cq201945_glm, file = "/Users/nooni/Box/RNR597_data/prediction/cq201945_glm.tif")
#writeRaster(cq201945_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/cq201945_h2o_glm.tif")
#writeRaster(cq202119_glm , file = "/Users/nooni/Box/RNR597_data/prediction/cq202119_glm.tif")
#writeRaster(cq202119_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/cq202119_h2o_glm.tif")
#writeRaster(cq202132_glm , file = "/Users/nooni/Box/RNR597_data/prediction/cq202132_glm.tif")
#writeRaster(cq202132_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/cq202132_h2o_glm.tif")
#writeRaster(cq202145_glm , file = "/Users/nooni/Box/RNR597_data/prediction/cq202145_glm.tif")
#writeRaster(cq202145_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/cq202145_h2o_glm.tif")


cq201319_glm<- raster("/Users/nooni/Box/RNR597_data/prediction/cq201319_glm.tif")

plot(cq201319_glm)

cq201319_h2o_glm<- raster("/Users/nooni/Box/RNR597_data/prediction/cq201319_h2o_glm.tif")

plot(cq201319_h2o_glm)
#**RF**
#rf_model_cq_h20 <- readRDS(here("Natalie/data_cleaned/models/rf_model_cq_h2o.rds"))
#rf_model_cq <- readRDS(here("Natalie/data_cleaned/models/rf_model_cq.rds"))

cq201319_rf <- predict(yw201319_cq, rf_model_cq) #without water
cq201319_h2o_rf <- predict(yw201319_cq_h2o, rf_model_cq_h20) #with water

cq201332_rf <- predict(yw201332_cq, rf_model_cq) #without water
cq201332_h2o_rf <- predict(yw201332_cq_h2o, rf_model_cq_h20) #with water

cq201345_rf <- predict(yw201345_cq, rf_model_cq) #without water
cq201345_h2o_rf <- predict(yw201345_cq_h2o, rf_model_cq_h20) #with water

cq201919_rf <- predict(yw201719_cq, rf_model_cq) #without water
cq201919_h2o_rf <- predict(yw201719_cq_h2o, rf_model_cq_h20) #with water

cq201932_rf <- predict(yw201732_cq, rf_model_cq) #without water
cq201932_h2o_rf <- predict(yw201732_cq_h2o, rf_model_cq_h20) #with water

cq201945_rf <- predict(yw201745_cq, rf_model_cq) #without water
cq201945_h2o_rf <- predict(yw201745_cq_h2o, rf_model_cq_h20) #with water

cq202119_rf <- predict(yw202119_cq, rf_model_cq) #without water
cq202119_h2o_rf <- predict(yw202119_cq_h2o, rf_model_cq_h20) #with water

cq202132_rf <- predict(yw202132_cq, rf_model_cq) #without water
cq202132_h2o_rf <- predict(yw202132_cq_h2o, rf_model_cq_h20) #with water

cq202145_rf <- predict(yw202145_cq, rf_model_cq) #without water
cq202145_h2o_rf <- predict(yw202145_cq_h2o, rf_model_cq_h20) #with water

#writeRaster(cq201319_rf, file = "/Users/nooni/Box/RNR597_data/prediction/cq201319_rf.tif")
#writeRaster(cq201319_h2o_rf, file = "/Users/nooni/Box/RNR597_data/prediction/cq201319_h2o_rf.tif")
#writeRaster(cq201332_rf, file = "/Users/nooni/Box/RNR597_data/prediction/cq201332_rf.tif")
#writeRaster(cq201332_h2o_rf, file = "/Users/nooni/Box/RNR597_data/prediction/cq201332_h2o_rf.tif")
#writeRaster(cq201345_rf, file = "/Users/nooni/Box/RNR597_data/prediction/cq201345_rf.tif")
#writeRaster(cq201345_h2o_rf, file = "/Users/nooni/Box/RNR597_data/prediction/cq201345_h2o_rf.tif")
#writeRaster(cq201919_rf, file = "/Users/nooni/Box/RNR597_data/prediction/cq201919_rf.tif")
#writeRaster(cq201345_h2o_rf, file = "/Users/nooni/Box/RNR597_data/prediction/cq201919_h2o_rf.tif")
#writeRaster(cq201919_rf, file = "/Users/nooni/Box/RNR597_data/prediction/cq201932_rf.tif")
#writeRaster(cq201932_h2o_rf, file = "/Users/nooni/Box/RNR597_data/prediction/cq201932_h2o_rf.tif")
#writeRaster(cq201945_rf, file = "/Users/nooni/Box/RNR597_data/prediction/cq201945_rf.tif")
#writeRaster(cq201945_h2o_rf, file = "/Users/nooni/Box/RNR597_data/prediction/cq201945_h2o_rf.tif")
#writeRaster(cq202119_rf , file = "/Users/nooni/Box/RNR597_data/prediction/cq202119_rf.tif")
#writeRaster(cq202119_h2o_rf, file = "/Users/nooni/Box/RNR597_data/prediction/cq202119_h2o_rf.tif")
#writeRaster(cq202132_rf , file = "/Users/nooni/Box/RNR597_data/prediction/cq202132_rf.tif")
#writeRaster(cq202132_h2o_rf, file = "/Users/nooni/Box/RNR597_data/prediction/cq202132_h2o_rf.tif")
#writeRaster(cq202145_rf , file = "/Users/nooni/Box/RNR597_data/prediction/cq202145_rf.tif")
#writeRaster(cq202145_h2o_rf, file = "/Users/nooni/Box/RNR597_data/prediction/cq202145_h2o_rf.tif")
```


ct-predict
```{r}
ct_subset <- c("prec1", "prec2", "tmin1", "tavg1", "tmax1", "humd2")
ct_subset_h2o <- c("prec1", "prec2", "tmin1", "tavg1", "tmax1", "humd2", "NDVI", "MNDWI")

#Subsetting years
yw201319_ct <- subset(YW201319_rast, ct_subset)
yw201319_ct_h2o <- subset(YW201319_rast, ct_subset_h2o)
yw201332_ct <-subset(yw201332_rast, ct_subset)
yw201332_ct_h2o <- subset(yw201332_rast, ct_subset_h2o)
yw201345_ct <-subset(yw201345_rast, ct_subset)
yw201345_ct_h2o<-subset(yw201345_rast, ct_subset_h2o)
yw201719_ct<-subset(yw201719_rast, ct_subset)
yw201719_ct_h2o <-subset(yw201719_rast, ct_subset_h2o)
yw201732_ct<-subset(yw201732_rast, ct_subset)
yw201732_ct_h2o <-subset(yw201732_rast, ct_subset_h2o)
yw201745_ct<-subset(yw201745_rast, ct_subset)
yw201745_ct_h2o <-subset(yw201745_rast, ct_subset_h2o)
yw202119_ct<-subset(yw202119_rast, ct_subset)
yw202119_ct_h2o <-subset(yw202119_rast, ct_subset_h2o)
yw202132_ct<-subset(yw202132_rast, ct_subset)
yw202132_ct_h2o <-subset(yw202132_rast, ct_subset_h2o)
yw202145_ct<-subset(yw202145_rast, ct_subset)
yw202145_ct_h2o <- subset(yw202145_rast, ct_subset_h2o)


#**GLM**
#glm_model_ct_h20 <- readRDS(here("Natalie/data_cleaned/models/glm_model_ct_h20.rds"))
#glm_model_ct <- readRDS(here("Natalie/data_cleaned/models/glm_model_ct.rds"))

ct201319_glm <- predict(yw201319_ct, glm_model_ct) #without water
ct201319_h2o_glm <- predict(yw201319_ct_h2o, glm_model_ct_h20) #with water

ct201332_glm <- predict(yw201332_ct, glm_model_ct) #without water
ct201332_h2o_glm <- predict(yw201332_ct_h2o, glm_model_ct_h20) #with water

ct201345_glm <- predict(yw201345_ct, glm_model_ct) #without water
ct201345_h2o_glm <- predict(yw201345_ct_h2o, glm_model_ct_h20) #with water

ct201919_glm <- predict(yw201719_ct, glm_model_ct) #without water
ct201919_h2o_glm <- predict(yw201719_ct_h2o, glm_model_ct_h20) #with water

ct201932_glm <- predict(yw201732_ct, glm_model_ct) #without water
ct201932_h2o_glm <- predict(yw201732_ct_h2o, glm_model_ct_h20) #with water

ct201945_glm <- predict(yw201745_ct, glm_model_ct) #without water
ct201945_h2o_glm <- predict(yw201745_ct_h2o, glm_model_ct_h20) #with water

ct202119_glm <- predict(yw202119_ct, glm_model_ct) #without water
ct202119_h2o_glm <- predict(yw202119_ct_h2o, glm_model_ct_h20) #with water

ct202132_glm <- predict(yw202132_ct, glm_model_ct) #without water
ct202132_h2o_glm <- predict(yw202132_ct_h2o, glm_model_ct_h20) #with water

ct202145_glm <- predict(yw202145_ct, glm_model_ct) #without water
ct202145_h2o_glm <- predict(yw202145_ct_h2o, glm_model_ct_h20) #with water


#writeRaster(ct201319_glm, file = "/Users/nooni/Box/RNR597_data/prediction/ct201319_glm.tif")
#writeRaster(ct201319_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/ct201319_h2o_glm.tif")
#writeRaster(ct201332_glm, file = "/Users/nooni/Box/RNR597_data/prediction/ct201332_glm.tif")
#writeRaster(ct201332_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/ct201332_h2o_glm.tif")
#writeRaster(ct201345_glm, file = "/Users/nooni/Box/RNR597_data/prediction/ct201345_glm.tif")
#writeRaster(ct201345_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/ct201345_h2o_glm.tif")
#writeRaster(ct201919_glm, file = "/Users/nooni/Box/RNR597_data/prediction/ct201919_glm.tif")
#writeRaster(ct201345_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/ct201919_h2o_glm.tif")
#writeRaster(ct201919_glm, file = "/Users/nooni/Box/RNR597_data/prediction/ct201932_glm.tif")
#writeRaster(ct201932_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/ct201932_h2o_glm.tif")
#writeRaster(ct201945_glm, file = "/Users/nooni/Box/RNR597_data/prediction/ct201945_glm.tif")
#writeRaster(ct201945_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/ct201945_h2o_glm.tif")
#writeRaster(ct202119_glm , file = "/Users/nooni/Box/RNR597_data/prediction/ct202119_glm.tif")
#writeRaster(ct202119_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/ct202119_h2o_glm.tif")
#writeRaster(ct202132_glm , file = "/Users/nooni/Box/RNR597_data/prediction/ct202132_glm.tif")
#writeRaster(ct202132_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/ct202132_h2o_glm.tif")
#writeRaster(ct202145_glm , file = "/Users/nooni/Box/RNR597_data/prediction/ct202145_glm.tif")
#writeRaster(ct202145_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/ct202145_h2o_glm.tif")

ct202145_h2o_glm<- rast(ct202145_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/ct202145_h2o_glm.tif")



#**RF**

rf_model_ct_h20 <- readRDS(here("Natalie/data_cleaned/models/rf_model_ct_h2o.rds"))
rf_model_ct <- readRDS(here("Natalie/data_cleaned/models/rf_model_ct.rds"))

ct201319_rf <- predict(yw201319_ct, rf_model_ct) #without water
ct201319_h2o_rf <- predict(yw201319_ct_h2o, rf_model_ct_h20) #with water

ct201332_rf <- predict(yw201332_ct, rf_model_ct) #without water
ct201332_h2o_rf <- predict(yw201332_ct_h2o, rf_model_ct_h20) #with water

ct201345_rf <- predict(yw201345_ct, rf_model_ct) #without water
ct201345_h2o_rf <- predict(yw201345_ct_h2o, rf_model_ct_h20) #with water

ct201919_rf <- predict(yw201719_ct, rf_model_ct) #without water
ct201919_h2o_rf <- predict(yw201719_ct_h2o, rf_model_ct_h20) #with water

ct201932_rf <- predict(yw201732_ct, rf_model_ct) #without water
ct201932_h2o_rf <- predict(yw201732_ct_h2o, rf_model_ct_h20) #with water

ct201945_rf <- predict(yw201745_ct, rf_model_ct) #without water
ct201945_h2o_rf <- predict(yw201745_ct_h2o, rf_model_ct_h20) #with water

ct202119_rf <- predict(yw202119_ct, rf_model_ct) #without water
ct202119_h2o_rf <- predict(yw202119_ct_h2o, rf_model_ct_h20) #with water

ct202132_rf <- predict(yw202132_ct, rf_model_ct) #without water
ct202132_h2o_rf <- predict(yw202132_ct_h2o, rf_model_ct_h20) #with water

ct202145_rf <- predict(yw202145_ct, rf_model_ct) #without water
ct202145_h2o_rf <- predict(yw202145_ct_h2o, rf_model_ct_h20) #with water


#writeRaster(ct201319_rf, file = "/Users/nooni/Box/RNR597_data/prediction/ct201319_rf.tif")
#writeRaster(ct201319_h2o_rf, file = "/Users/nooni/Box/RNR597_data/prediction/ct201319_h2o_rf.tif")
#writeRaster(ct201332_rf, file = "/Users/nooni/Box/RNR597_data/prediction/ct201332_rf.tif")
#writeRaster(ct201332_h2o_rf, file = "/Users/nooni/Box/RNR597_data/prediction/ct201332_h2o_rf.tif")
#writeRaster(ct201345_rf, file = "/Users/nooni/Box/RNR597_data/prediction/ct201345_rf.tif")
#writeRaster(ct201345_h2o_rf, file = "/Users/nooni/Box/RNR597_data/prediction/ct201345_h2o_rf.tif")
#writeRaster(ct201919_rf, file = "/Users/nooni/Box/RNR597_data/prediction/ct201919_rf.tif")
#writeRaster(ct201345_h2o_rf, file = "/Users/nooni/Box/RNR597_data/prediction/ct201919_h2o_rf.tif")
#writeRaster(ct201919_rf, file = "/Users/nooni/Box/RNR597_data/prediction/ct201932_rf.tif")
#writeRaster(ct201932_h2o_rf, file = "/Users/nooni/Box/RNR597_data/prediction/ct201932_h2o_rf.tif")
#writeRaster(ct201945_rf, file = "/Users/nooni/Box/RNR597_data/prediction/ct201945_rf.tif")
#writeRaster(ct201945_h2o_rf, file = "/Users/nooni/Box/RNR597_data/prediction/ct201945_h2o_rf.tif")
#writeRaster(ct202119_rf , file = "/Users/nooni/Box/RNR597_data/prediction/ct202119_rf.tif")
#writeRaster(ct202119_h2o_rf, file = "/Users/nooni/Box/RNR597_data/prediction/ct202119_h2o_rf.tif")
#writeRaster(ct202132_rf , file = "/Users/nooni/Box/RNR597_data/prediction/ct202132_rf.tif")
#writeRaster(ct202132_h2o_rf, file = "/Users/nooni/Box/RNR597_data/prediction/ct202132_h2o_rf.tif")
#writeRaster(ct202145_rf , file = "/Users/nooni/Box/RNR597_data/prediction/ct202145_rf.tif")
#writeRaster(ct202145_h2o_rf, file = "/Users/nooni/Box/RNR597_data/prediction/ct202145_h2o_rf.tif")

```

aa-predict 
```{r}
aa_subset <- c("prec1", "prec2", "tmin2", "tavg2", "humd2", "tmax2")
aa_subset_h2o <- c("prec1", "prec2", "tmin2", "tavg2", "humd2", "tmax2", "NDVI", "MNDWI")

#Subsetting years
yw201319_aa <- subset(YW201319_rast, aa_subset)
yw201319_aa_h2o <- subset(YW201319_rast, aa_subset_h2o)
yw201332_aa <-subset(yw201332_rast, aa_subset)
yw201332_aa_h2o <- subset(yw201332_rast, aa_subset_h2o)
yw201345_aa <-subset(yw201345_rast, aa_subset)
yw201345_aa_h2o<-subset(yw201345_rast, aa_subset_h2o)
yw201719_aa<-subset(yw201719_rast, aa_subset)
yw201719_aa_h2o <-subset(yw201719_rast, aa_subset_h2o)
yw201732_aa<-subset(yw201732_rast, aa_subset)
yw201732_aa_h2o <-subset(yw201732_rast, aa_subset_h2o)
yw201745_aa<-subset(yw201745_rast, aa_subset)
yw201745_aa_h2o <-subset(yw201745_rast, aa_subset_h2o)
yw202119_aa<-subset(yw202119_rast, aa_subset)
yw202119_aa_h2o <-subset(yw202119_rast, aa_subset_h2o)
yw202132_aa<-subset(yw202132_rast, aa_subset)
yw202132_aa_h2o <-subset(yw202132_rast, aa_subset_h2o)
yw202145_aa<-subset(yw202145_rast, aa_subset)
yw202145_aa_h2o <- subset(yw202145_rast, aa_subset_h2o)


#**GLM**

#glm_model_aa_h20 <- readRDS(here("Natalie/data_cleaned/models/glm_model_aa_h20.rds"))
#glm_model_aa <- readRDS(here("Natalie/data_cleaned/models/glm_model_aa.rds"))

aa201319_glm <- predict(yw201319_aa, glm_model_aa) #without water
aa201319_h2o_glm <- predict(yw201319_aa_h2o, glm_model_aa_h20) #with water

aa201332_glm <- predict(yw201332_aa, glm_model_aa) #without water
aa201332_h2o_glm <- predict(yw201332_aa_h2o, glm_model_aa_h20) #with water

aa201345_glm <- predict(yw201345_aa, glm_model_aa) #without water
aa201345_h2o_glm <- predict(yw201345_aa_h2o, glm_model_aa_h20) #with water

aa201919_glm <- predict(yw201719_aa, glm_model_aa) #without water
aa201919_h2o_glm <- predict(yw201719_aa_h2o, glm_model_aa_h20) #with water

aa201932_glm <- predict(yw201732_aa, glm_model_aa) #without water
aa201932_h2o_glm <- predict(yw201732_aa_h2o, glm_model_aa_h20) #with water

aa201945_glm <- predict(yw201745_aa, glm_model_aa) #without water
aa201945_h2o_glm <- predict(yw201745_aa_h2o, glm_model_aa_h20) #with water

aa202119_glm <- predict(yw202119_aa, glm_model_aa) #without water
aa202119_h2o_glm <- predict(yw202119_aa_h2o, glm_model_aa_h20) #with water

aa202132_glm <- predict(yw202132_aa, glm_model_aa) #without water
aa202132_h2o_glm <- predict(yw202132_aa_h2o, glm_model_aa_h20) #with water

aa202145_glm <- predict(yw202145_aa, glm_model_aa) #without water
aa202145_h2o_glm <- predict(yw202145_aa_h2o, glm_model_aa_h20) #with water


#writeRaster(aa201319_glm, file = "/Users/nooni/Box/RNR597_data/prediction/aa201319_glm.tif")
#writeRaster(aa201319_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/aa201319_h2o_glm.tif")
#writeRaster(aa201332_glm, file = "/Users/nooni/Box/RNR597_data/prediction/aa201332_glm.tif")
#writeRaster(aa201332_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/aa201332_h2o_glm.tif")
#writeRaster(aa201345_glm, file = "/Users/nooni/Box/RNR597_data/prediction/aa201345_glm.tif")
#writeRaster(aa201345_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/aa201345_h2o_glm.tif")
#writeRaster(aa201919_glm, file = "/Users/nooni/Box/RNR597_data/prediction/aa201919_glm.tif")
#writeRaster(aa201345_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/aa201919_h2o_glm.tif")
#writeRaster(aa201919_glm, file = "/Users/nooni/Box/RNR597_data/prediction/aa201932_glm.tif")
#writeRaster(aa201932_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/aa201932_h2o_glm.tif")
#writeRaster(aa201945_glm, file = "/Users/nooni/Box/RNR597_data/prediction/aa201945_glm.tif")
#writeRaster(aa201945_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/aa201945_h2o_glm.tif")
#writeRaster(aa202119_glm , file = "/Users/nooni/Box/RNR597_data/prediction/aa202119_glm.tif")
#writeRaster(aa202119_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/aa202119_h2o_glm.tif")
#writeRaster(aa202132_glm , file = "/Users/nooni/Box/RNR597_data/prediction/aa202132_glm.tif")
#writeRaster(aa202132_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/aa202132_h2o_glm.tif")
#writeRaster(aa202145_glm , file = "/Users/nooni/Box/RNR597_data/prediction/aa202145_glm.tif")
#writeRaster(aa202145_h2o_glm, file = "/Users/nooni/Box/RNR597_data/prediction/aa202145_h2o_glm.tif")


#**RF**
rf_model_aa_h20 <- readRDS(here("Natalie/data_cleaned/models/rf_model_aa_h2o.rds"))
rf_model_aa <- readRDS(here("Natalie/data_cleaned/models/rf_model_aa.rds"))

aa201319_rf <- predict(yw201319_aa, rf_model_aa) #without water
aa201319_h2o_rf <- predict(yw201319_aa_h2o, rf_model_aa_h20) #with water

aa201332_rf <- predict(yw201332_aa, rf_model_aa) #without water
aa201332_h2o_rf <- predict(yw201332_aa_h2o, rf_model_aa_h20) #with water

aa201345_rf <- predict(yw201345_aa, rf_model_aa) #without water
aa201345_h2o_rf <- predict(yw201345_aa_h2o, rf_model_aa_h20) #with water

aa201919_rf <- predict(yw201719_aa, rf_model_aa) #without water
aa201919_h2o_rf <- predict(yw201719_aa_h2o, rf_model_aa_h20) #with water

aa201932_rf <- predict(yw201732_aa, rf_model_aa) #without water
aa201932_h2o_rf <- predict(yw201732_aa_h2o, rf_model_aa_h20) #with water

aa201945_rf <- predict(yw201745_aa, rf_model_aa) #without water
aa201945_h2o_rf <- predict(yw201745_aa_h2o, rf_model_aa_h20) #with water

aa202119_rf <- predict(yw202119_aa, rf_model_aa) #without water
aa202119_h2o_rf <- predict(yw202119_aa_h2o, rf_model_aa_h20) #with water

aa202132_rf <- predict(yw202132_aa, rf_model_aa) #without water
aa202132_h2o_rf <- predict(yw202132_aa_h2o, rf_model_aa_h20) #with water

aa202145_rf <- predict(yw202145_aa, rf_model_aa) #without water
aa202145_h2o_rf <- predict(yw202145_aa_h2o, rf_model_aa_h20) #with water


#writeRaster(aa201319_rf, file = "/Users/nooni/Box/RNR597_data/prediction/aa201319_rf.tif")
#writeRaster(aa201319_h2o_rf, file = "/Users/nooni/Box/RNR597_data/prediction/aa201319_h2o_rf.tif")
#writeRaster(aa201332_rf, file = "/Users/nooni/Box/RNR597_data/prediction/aa201332_rf.tif")
#writeRaster(aa201332_h2o_rf, file = "/Users/nooni/Box/RNR597_data/prediction/aa201332_h2o_rf.tif")
#writeRaster(aa201345_rf, file = "/Users/nooni/Box/RNR597_data/prediction/aa201345_rf.tif")
#writeRaster(aa201345_h2o_rf, file = "/Users/nooni/Box/RNR597_data/prediction/aa201345_h2o_rf.tif")
#writeRaster(aa201919_rf, file = "/Users/nooni/Box/RNR597_data/prediction/aa201919_rf.tif")
#writeRaster(aa201345_h2o_rf, file = "/Users/nooni/Box/RNR597_data/prediction/aa201919_h2o_rf.tif")
#writeRaster(aa201919_rf, file = "/Users/nooni/Box/RNR597_data/prediction/aa201932_rf.tif")
#writeRaster(aa201932_h2o_rf, file = "/Users/nooni/Box/RNR597_data/prediction/aa201932_h2o_rf.tif")
#writeRaster(aa201945_rf, file = "/Users/nooni/Box/RNR597_data/prediction/aa201945_rf.tif")
#writeRaster(aa201945_h2o_rf, file = "/Users/nooni/Box/RNR597_data/prediction/aa201945_h2o_rf.tif")
#writeRaster(aa202119_rf , file = "/Users/nooni/Box/RNR597_data/prediction/aa202119_rf.tif")
#writeRaster(aa202119_h2o_rf, file = "/Users/nooni/Box/RNR597_data/prediction/aa202119_h2o_rf.tif")
#writeRaster(aa202132_rf , file = "/Users/nooni/Box/RNR597_data/prediction/aa202132_rf.tif")
#writeRaster(aa202132_h2o_rf, file = "/Users/nooni/Box/RNR597_data/prediction/aa202132_h2o_rf.tif")
#writeRaster(aa202145_rf , file = "/Users/nooni/Box/RNR597_data/prediction/aa202145_rf.tif")
#writeRaster(aa202145_h2o_rf, file = "/Users/nooni/Box/RNR597_data/prediction/aa202145_h2o_rf.tif")


```



AUC Values - cq
```{r}
#**cq**
#train_data_cq <- read.csv(here("Natalie/data_cleaned/test_train/train_data_cq.csv"))
test_data_cq <- read.csv(here("Natalie/data_cleaned/test_train/test_data_cq.csv"))
test_coords_cq <- test_data_cq[, c("Longitude", "Latitude")]
test_presence_cq <- as.numeric(test_data_cq$cq)

#**YW201319**
#glm_h20
#cq201319_h2o_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq201319_h2o_glm.tif")
glm_test_pred_cq201319_h2o <- extract(cq201319_h2o_glm, test_coords_cq, pos_label =1)
glm_DFauc_cq201319_h2o <- data.frame(test_data_cq$X, test_presence_cq, glm_test_pred_cq201319_h2o)
glm_auc_cq201319_h2o <- PresenceAbsence ::auc(glm_DFauc_cq201319_h2o, which.model = TRUE, na.rm=TRUE)

#glm
#cq201319_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq201319_glm.tif")
glm_test_pred_cq201319<- extract(cq201319_glm, test_coords_cq, pos_label =1)
glm_DFauc_cq201319 <- data.frame(test_data_cq$X, test_presence_cq, glm_test_pred_cq201319)
glm_auc_cq201319 <- PresenceAbsence ::auc(glm_DFauc_cq201319, which.model = TRUE, na.rm=TRUE)

#rf_h20
#cq201319_h2o_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq201319_h2o_rf.tif")
rf_test_pred_cq201319_h2o <- extract(cq201319_h2o_rf, test_coords_cq, pos_label =1)
rf_DFauc_cq201319_h2o <- data.frame(test_data_cq$X, test_presence_cq, rf_test_pred_cq201319_h2o)
rf_auc_cq201319_h2o <- PresenceAbsence ::auc(rf_DFauc_cq201319_h2o, which.model = TRUE, na.rm=TRUE)

#rf
#cq201319_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq201319_rf.tif")
rf_test_pred_cq201319<- extract(cq201319_rf, test_coords_cq, pos_label =1)
rf_DFauc_cq201319 <- data.frame(test_data_cq$X, test_presence_cq, rf_test_pred_cq201319)
rf_auc_cq201319 <- PresenceAbsence ::auc(rf_DFauc_cq201319, which.model = TRUE, na.rm=TRUE)


##**AUC Dataframe**
auc_cq_201319_h2o <- rbind(glm_auc_cq201319_h2o, rf_auc_cq201319_h2o)
colnames(auc_cq_201319_h2o) <- c("AUC", "StdDev")
rownames(auc_cq_201319_h2o) <-c("GLM", "Rf")

auc_cq_201319 <- rbind(glm_auc_cq201319, rf_auc_cq201319)
colnames(auc_cq_201319) <- c("AUC", "StdDev")
rownames(auc_cq_201319) <-c("GLM", "Rf")

#write.csv(auc_cq_201319_h2o, "C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_201319_h2o.csv")
#write.csv(auc_cq_201319, "C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_201319.csv")



#**YW201332**
#glm_h20
cq201332_h2o_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq201332_h2o_glm.tif")
glm_test_pred_cq201332_h2o <- extract(cq201332_h2o_glm, test_coords_cq, pos_label =1)
glm_DFauc_cq201332_h2o <- data.frame(test_data_cq$X, test_presence_cq, glm_test_pred_cq201332_h2o)
glm_auc_cq201332_h2o <- PresenceAbsence ::auc(glm_DFauc_cq201332_h2o, which.model = TRUE, na.rm=TRUE)

#glm
cq201332_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq201332_glm.tif")
glm_test_pred_cq201332<- extract(cq201332_glm, test_coords_cq, pos_label =1)
glm_DFauc_cq201332 <- data.frame(test_data_cq$X, test_presence_cq, glm_test_pred_cq201332)
glm_auc_cq201332 <- PresenceAbsence ::auc(glm_DFauc_cq201332, which.model = TRUE, na.rm=TRUE)

#rf_h20
cq201332_h2o_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq201332_h2o_rf.tif")
rf_test_pred_cq201332_h2o <- extract(cq201332_h2o_rf, test_coords_cq, pos_label =1)
rf_DFauc_cq201332_h2o <- data.frame(test_data_cq$X, test_presence_cq, rf_test_pred_cq201332_h2o)
rf_auc_cq201332_h2o <- PresenceAbsence ::auc(rf_DFauc_cq201332_h2o, which.model = TRUE, na.rm=TRUE)

#rf
cq201332_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq201332_rf.tif")
rf_test_pred_cq201332<- extract(cq201332_rf, test_coords_cq, pos_label =1)
rf_DFauc_cq201332 <- data.frame(test_data_cq$X, test_presence_cq, rf_test_pred_cq201332)
rf_auc_cq201332 <- PresenceAbsence ::auc(rf_DFauc_cq201332, which.model = TRUE, na.rm=TRUE)


##**AUC Dataframe**
auc_cq_201332_h2o <- rbind(glm_auc_cq201332_h2o, rf_auc_cq201332_h2o)
colnames(auc_cq_201332_h2o) <- c("AUC", "StdDev")
rownames(auc_cq_201332_h2o) <-c("GLM", "Rf")

auc_cq_201332 <- rbind(glm_auc_cq201332, rf_auc_cq201332)
colnames(auc_cq_201332) <- c("AUC", "StdDev")
rownames(auc_cq_201332) <-c("GLM", "Rf")

write.csv(auc_cq_201332_h2o, "C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_201332_h2o.csv")
write.csv(auc_cq_201332, "C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_201332.csv")



#**YW201345**
#glm_h20
cq201345_h2o_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq201345_h2o_glm.tif")
glm_test_pred_cq201345_h2o <- extract(cq201345_h2o_glm, test_coords_cq, pos_label =1)
glm_DFauc_cq201345_h2o <- data.frame(test_data_cq$X, test_presence_cq, glm_test_pred_cq201345_h2o)
glm_auc_cq201345_h2o <- PresenceAbsence ::auc(glm_DFauc_cq201345_h2o, which.model = TRUE, na.rm=TRUE)

#glm
cq201345_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq201345_glm.tif")
glm_test_pred_cq201345<- extract(cq201345_glm, test_coords_cq, pos_label =1)
glm_DFauc_cq201345 <- data.frame(test_data_cq$X, test_presence_cq, glm_test_pred_cq201345)
glm_auc_cq201345 <- PresenceAbsence ::auc(glm_DFauc_cq201345, which.model = TRUE, na.rm=TRUE)

#rf_h20
cq201345_h2o_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq201345_h2o_rf.tif")
rf_test_pred_cq201345_h2o <- extract(cq201345_h2o_rf, test_coords_cq, pos_label =1)
rf_DFauc_cq201345_h2o <- data.frame(test_data_cq$X, test_presence_cq, rf_test_pred_cq201345_h2o)
rf_auc_cq201345_h2o <- PresenceAbsence ::auc(rf_DFauc_cq201345_h2o, which.model = TRUE, na.rm=TRUE)

#rf
cq201345_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq201345_rf.tif")
rf_test_pred_cq201345<- extract(cq201345_rf, test_coords_cq, pos_label =1)
rf_DFauc_cq201345 <- data.frame(test_data_cq$X, test_presence_cq, rf_test_pred_cq201345)
rf_auc_cq201345 <- PresenceAbsence ::auc(rf_DFauc_cq201345, which.model = TRUE, na.rm=TRUE)


##**AUC Dataframe**
auc_cq_201345_h2o <- rbind(glm_auc_cq201345_h2o, rf_auc_cq201345_h2o)
colnames(auc_cq_201345_h2o) <- c("AUC", "StdDev")
rownames(auc_cq_201345_h2o) <-c("GLM", "Rf")

auc_cq_201345 <- rbind(glm_auc_cq201345, rf_auc_cq201345)
colnames(auc_cq_201345) <- c("AUC", "StdDev")
rownames(auc_cq_201345) <-c("GLM", "Rf")

write.csv(auc_cq_201345_h2o, "C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_201345_h2o.csv")
write.csv(auc_cq_201345, "C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_201345.csv")



#**YW201919**
#glm_h20
cq201919_h2o_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq201919_h2o_glm.tif")
glm_test_pred_cq201919_h2o <- extract(cq201919_h2o_glm, test_coords_cq, pos_label =1)
glm_DFauc_cq201919_h2o <- data.frame(test_data_cq$X, test_presence_cq, glm_test_pred_cq201919_h2o)
glm_auc_cq201919_h2o <- PresenceAbsence ::auc(glm_DFauc_cq201919_h2o, which.model = TRUE, na.rm=TRUE)

#glm
cq201919_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq201919_glm.tif")
glm_test_pred_cq201919<- extract(cq201919_glm, test_coords_cq, pos_label =1)
glm_DFauc_cq201919 <- data.frame(test_data_cq$X, test_presence_cq, glm_test_pred_cq201919)
glm_auc_cq201919 <- PresenceAbsence ::auc(glm_DFauc_cq201919, which.model = TRUE, na.rm=TRUE)

#rf_h20
cq201919_h2o_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq201919_h2o_rf.tif")
rf_test_pred_cq201919_h2o <- extract(cq201919_h2o_rf, test_coords_cq, pos_label =1)
rf_DFauc_cq201919_h2o <- data.frame(test_data_cq$X, test_presence_cq, rf_test_pred_cq201919_h2o)
rf_auc_cq201919_h2o <- PresenceAbsence ::auc(rf_DFauc_cq201919_h2o, which.model = TRUE, na.rm=TRUE)

#rf
cq201919_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq201919_rf.tif")
rf_test_pred_cq201919<- extract(cq201919_rf, test_coords_cq, pos_label =1)
rf_DFauc_cq201919 <- data.frame(test_data_cq$X, test_presence_cq, rf_test_pred_cq201919)
rf_auc_cq201919 <- PresenceAbsence ::auc(rf_DFauc_cq201919, which.model = TRUE, na.rm=TRUE)


##**AUC Dataframe**
auc_cq_201919_h2o <- rbind(glm_auc_cq201919_h2o, rf_auc_cq201919_h2o)
colnames(auc_cq_201919_h2o) <- c("AUC", "StdDev")
rownames(auc_cq_201919_h2o) <-c("GLM", "Rf")

auc_cq_201919 <- rbind(glm_auc_cq201919, rf_auc_cq201919)
colnames(auc_cq_201919) <- c("AUC", "StdDev")
rownames(auc_cq_201919) <-c("GLM", "Rf")

write.csv(auc_cq_201919_h2o, "C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_201919_h2o.csv")
write.csv(auc_cq_201919, "C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_201919.csv")



#**YW201932**
#glm_h20
cq201932_h2o_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq201932_h2o_glm.tif")
glm_test_pred_cq201932_h2o <- extract(cq201932_h2o_glm, test_coords_cq, pos_label =1)
glm_DFauc_cq201932_h2o <- data.frame(test_data_cq$X, test_presence_cq, glm_test_pred_cq201932_h2o)
glm_auc_cq201932_h2o <- PresenceAbsence ::auc(glm_DFauc_cq201932_h2o, which.model = TRUE, na.rm=TRUE)

#glm
cq201932_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq201932_glm.tif")
glm_test_pred_cq201932<- extract(cq201932_glm, test_coords_cq, pos_label =1)
glm_DFauc_cq201932 <- data.frame(test_data_cq$X, test_presence_cq, glm_test_pred_cq201932)
glm_auc_cq201932 <- PresenceAbsence ::auc(glm_DFauc_cq201932, which.model = TRUE, na.rm=TRUE)

#rf_h20
cq201932_h2o_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq201932_h2o_rf.tif")
rf_test_pred_cq201932_h2o <- extract(cq201932_h2o_rf, test_coords_cq, pos_label =1)
rf_DFauc_cq201932_h2o <- data.frame(test_data_cq$X, test_presence_cq, rf_test_pred_cq201932_h2o)
rf_auc_cq201932_h2o <- PresenceAbsence ::auc(rf_DFauc_cq201932_h2o, which.model = TRUE, na.rm=TRUE)

#rf
cq201932_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq201932_rf.tif")
rf_test_pred_cq201932<- extract(cq201932_rf, test_coords_cq, pos_label =1)
rf_DFauc_cq201932 <- data.frame(test_data_cq$X, test_presence_cq, rf_test_pred_cq201932)
rf_auc_cq201932 <- PresenceAbsence ::auc(rf_DFauc_cq201932, which.model = TRUE, na.rm=TRUE)


##**AUC Dataframe**
auc_cq_201932_h2o <- rbind(glm_auc_cq201932_h2o, rf_auc_cq201932_h2o)
colnames(auc_cq_201932_h2o) <- c("AUC", "StdDev")
rownames(auc_cq_201932_h2o) <-c("GLM", "Rf")

auc_cq_201932 <- rbind(glm_auc_cq201932, rf_auc_cq201932)
colnames(auc_cq_201932) <- c("AUC", "StdDev")
rownames(auc_cq_201932) <-c("GLM", "Rf")

write.csv(auc_cq_201932_h2o, "C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_201932_h2o.csv")
write.csv(auc_cq_201932, "C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_201932.csv")



#**YW201945**
#glm_h20
cq201945_h2o_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq201945_h2o_glm.tif")
glm_test_pred_cq201945_h2o <- extract(cq201945_h2o_glm, test_coords_cq, pos_label =1)
glm_DFauc_cq201945_h2o <- data.frame(test_data_cq$X, test_presence_cq, glm_test_pred_cq201945_h2o)
glm_auc_cq201945_h2o <- PresenceAbsence ::auc(glm_DFauc_cq201945_h2o, which.model = TRUE, na.rm=TRUE)

#glm
cq201945_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq201945_glm.tif")
glm_test_pred_cq201945<- extract(cq201945_glm, test_coords_cq, pos_label =1)
glm_DFauc_cq201945 <- data.frame(test_data_cq$X, test_presence_cq, glm_test_pred_cq201945)
glm_auc_cq201945 <- PresenceAbsence ::auc(glm_DFauc_cq201945, which.model = TRUE, na.rm=TRUE)

#rf_h20
cq201945_h2o_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq201945_h2o_rf.tif")
rf_test_pred_cq201945_h2o <- extract(cq201945_h2o_rf, test_coords_cq, pos_label =1)
rf_DFauc_cq201945_h2o <- data.frame(test_data_cq$X, test_presence_cq, rf_test_pred_cq201945_h2o)
rf_auc_cq201945_h2o <- PresenceAbsence ::auc(rf_DFauc_cq201945_h2o, which.model = TRUE, na.rm=TRUE)

#rf
cq201945_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq201945_rf.tif")
rf_test_pred_cq201945<- extract(cq201945_rf, test_coords_cq, pos_label =1)
rf_DFauc_cq201945 <- data.frame(test_data_cq$X, test_presence_cq, rf_test_pred_cq201945)
rf_auc_cq201945 <- PresenceAbsence ::auc(rf_DFauc_cq201945, which.model = TRUE, na.rm=TRUE)


##**AUC Dataframe**
auc_cq_201945_h2o <- rbind(glm_auc_cq201945_h2o, rf_auc_cq201945_h2o)
colnames(auc_cq_201945_h2o) <- c("AUC", "StdDev")
rownames(auc_cq_201945_h2o) <-c("GLM", "Rf")

auc_cq_201945 <- rbind(glm_auc_cq201945, rf_auc_cq201945)
colnames(auc_cq_201945) <- c("AUC", "StdDev")
rownames(auc_cq_201945) <-c("GLM", "Rf")

write.csv(auc_cq_201945_h2o, "C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_201945_h2o.csv")
write.csv(auc_cq_201945, "C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_201945.csv")



#**YW202119**
#glm_h20
cq202119_h2o_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq202119_h2o_glm.tif")
glm_test_pred_cq202119_h2o <- extract(cq202119_h2o_glm, test_coords_cq, pos_label =1)
glm_DFauc_cq202119_h2o <- data.frame(test_data_cq$X, test_presence_cq, glm_test_pred_cq202119_h2o)
glm_auc_cq202119_h2o <- PresenceAbsence ::auc(glm_DFauc_cq202119_h2o, which.model = TRUE, na.rm=TRUE)

#glm
cq202119_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq202119_glm.tif")
glm_test_pred_cq202119<- extract(cq202119_glm, test_coords_cq, pos_label =1)
glm_DFauc_cq202119 <- data.frame(test_data_cq$X, test_presence_cq, glm_test_pred_cq202119)
glm_auc_cq202119 <- PresenceAbsence ::auc(glm_DFauc_cq202119, which.model = TRUE, na.rm=TRUE)

#rf_h20
cq202119_h2o_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq202119_h2o_rf.tif")
rf_test_pred_cq202119_h2o <- extract(cq202119_h2o_rf, test_coords_cq, pos_label =1)
rf_DFauc_cq202119_h2o <- data.frame(test_data_cq$X, test_presence_cq, rf_test_pred_cq202119_h2o)
rf_auc_cq202119_h2o <- PresenceAbsence ::auc(rf_DFauc_cq202119_h2o, which.model = TRUE, na.rm=TRUE)

#rf
cq202119_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq202119_rf.tif")
rf_test_pred_cq202119<- extract(cq202119_rf, test_coords_cq, pos_label =1)
rf_DFauc_cq202119 <- data.frame(test_data_cq$X, test_presence_cq, rf_test_pred_cq202119)
rf_auc_cq202119 <- PresenceAbsence ::auc(rf_DFauc_cq202119, which.model = TRUE, na.rm=TRUE)


##**AUC Dataframe**
auc_cq_202119_h2o <- rbind(glm_auc_cq202119_h2o, rf_auc_cq202119_h2o)
colnames(auc_cq_202119_h2o) <- c("AUC", "StdDev")
rownames(auc_cq_202119_h2o) <-c("GLM", "Rf")

auc_cq_202119 <- rbind(glm_auc_cq202119, rf_auc_cq202119)
colnames(auc_cq_202119) <- c("AUC", "StdDev")
rownames(auc_cq_202119) <-c("GLM", "Rf")

write.csv(auc_cq_202119_h2o, "C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_202119_h2o.csv")
write.csv(auc_cq_202119, "C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_202119.csv")



#**YW202132**
#glm_h20
cq202132_h2o_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq202132_h2o_glm.tif")
glm_test_pred_cq202132_h2o <- extract(cq202132_h2o_glm, test_coords_cq, pos_label =1)
glm_DFauc_cq202132_h2o <- data.frame(test_data_cq$X, test_presence_cq, glm_test_pred_cq202132_h2o)
glm_auc_cq202132_h2o <- PresenceAbsence ::auc(glm_DFauc_cq202132_h2o, which.model = TRUE, na.rm=TRUE)

#glm
cq202132_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq202132_glm.tif")
glm_test_pred_cq202132<- extract(cq202132_glm, test_coords_cq, pos_label =1)
glm_DFauc_cq202132 <- data.frame(test_data_cq$X, test_presence_cq, glm_test_pred_cq202132)
glm_auc_cq202132 <- PresenceAbsence ::auc(glm_DFauc_cq202132, which.model = TRUE, na.rm=TRUE)

#rf_h20
cq202132_h2o_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq202132_h2o_rf.tif")
rf_test_pred_cq202132_h2o <- extract(cq202132_h2o_rf, test_coords_cq, pos_label =1)
rf_DFauc_cq202132_h2o <- data.frame(test_data_cq$X, test_presence_cq, rf_test_pred_cq202132_h2o)
rf_auc_cq202132_h2o <- PresenceAbsence ::auc(rf_DFauc_cq202132_h2o, which.model = TRUE, na.rm=TRUE)

#rf
cq202132_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq202132_rf.tif")
rf_test_pred_cq202132<- extract(cq202132_rf, test_coords_cq, pos_label =1)
rf_DFauc_cq202132 <- data.frame(test_data_cq$X, test_presence_cq, rf_test_pred_cq202132)
rf_auc_cq202132 <- PresenceAbsence ::auc(rf_DFauc_cq202132, which.model = TRUE, na.rm=TRUE)


##**AUC Dataframe**
auc_cq_202132_h2o <- rbind(glm_auc_cq202132_h2o, rf_auc_cq202132_h2o)
colnames(auc_cq_202132_h2o) <- c("AUC", "StdDev")
rownames(auc_cq_202132_h2o) <-c("GLM", "Rf")

auc_cq_202132 <- rbind(glm_auc_cq202132, rf_auc_cq202132)
colnames(auc_cq_202132) <- c("AUC", "StdDev")
rownames(auc_cq_202132) <-c("GLM", "Rf")

write.csv(auc_cq_202132_h2o, "C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_202132_h2o.csv")
write.csv(auc_cq_202132, "C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_202132.csv")



#**YW202145**
#glm_h20
cq202145_h2o_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq202145_h2o_glm.tif")
glm_test_pred_cq202145_h2o <- extract(cq202145_h2o_glm, test_coords_cq, pos_label =1)
glm_DFauc_cq202145_h2o <- data.frame(test_data_cq$X, test_presence_cq, glm_test_pred_cq202145_h2o)
glm_auc_cq202145_h2o <- PresenceAbsence ::auc(glm_DFauc_cq202145_h2o, which.model = TRUE, na.rm=TRUE)

#glm
cq202145_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq202145_glm.tif")
glm_test_pred_cq202145<- extract(cq202145_glm, test_coords_cq, pos_label =1)
glm_DFauc_cq202145 <- data.frame(test_data_cq$X, test_presence_cq, glm_test_pred_cq202145)
glm_auc_cq202145 <- PresenceAbsence ::auc(glm_DFauc_cq202145, which.model = TRUE, na.rm=TRUE)

#rf_h20
cq202145_h2o_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq202145_h2o_rf.tif")
rf_test_pred_cq202145_h2o <- extract(cq202145_h2o_rf, test_coords_cq, pos_label =1)
rf_DFauc_cq202145_h2o <- data.frame(test_data_cq$X, test_presence_cq, rf_test_pred_cq202145_h2o)
rf_auc_cq202145_h2o <- PresenceAbsence ::auc(rf_DFauc_cq202145_h2o, which.model = TRUE, na.rm=TRUE)

#rf
cq202145_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/cq202145_rf.tif")
rf_test_pred_cq202145<- extract(cq202145_rf, test_coords_cq, pos_label =1)
rf_DFauc_cq202145 <- data.frame(test_data_cq$X, test_presence_cq, rf_test_pred_cq202145)
rf_auc_cq202145 <- PresenceAbsence ::auc(rf_DFauc_cq202145, which.model = TRUE, na.rm=TRUE)


##**AUC Dataframe**
auc_cq_202145_h2o <- rbind(glm_auc_cq202145_h2o, rf_auc_cq202145_h2o)
colnames(auc_cq_202145_h2o) <- c("AUC", "StdDev")
rownames(auc_cq_202145_h2o) <-c("GLM", "Rf")

auc_cq_202145 <- rbind(glm_auc_cq202145, rf_auc_cq202145)
colnames(auc_cq_202145) <- c("AUC", "StdDev")
rownames(auc_cq_202145) <-c("GLM", "Rf")

write.csv(auc_cq_202145_h2o, "C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_202145_h2o.csv")
write.csv(auc_cq_202145, "C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_202145.csv")




```

AUC CT
```{r}
#**ct**
train_data_ct <- read.csv(here("Natalie/data_cleaned/test_train/train_data_ct.csv"))
test_data_ct <- read.csv(here("Natalie/data_cleaned/test_train/test_data_ct.csv"))
test_coords_ct <- test_data_ct[, c("Longitude", "Latitude")]
test_presence_ct <- as.numeric(test_data_ct$ct)

#**YW201319**
#glm_h20
ct201319_h2o_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct201319_h2o_glm.tif")
glm_test_pred_ct201319_h2o <- extract(ct201319_h2o_glm, test_coords_ct, pos_label =1)
glm_DFauc_ct201319_h2o <- data.frame(test_data_ct$X, test_presence_ct, glm_test_pred_ct201319_h2o)
glm_auc_ct201319_h2o <- PresenceAbsence ::auc(glm_DFauc_ct201319_h2o, which.model = TRUE, na.rm=TRUE)

#glm
ct201319_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct201319_glm.tif")
glm_test_pred_ct201319<- extract(ct201319_glm, test_coords_ct, pos_label =1)
glm_DFauc_ct201319 <- data.frame(test_data_ct$X, test_presence_ct, glm_test_pred_ct201319)
glm_auc_ct201319 <- PresenceAbsence ::auc(glm_DFauc_ct201319, which.model = TRUE, na.rm=TRUE)

#rf_h20
ct201319_h2o_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct201319_h2o_rf.tif")
rf_test_pred_ct201319_h2o <- extract(ct201319_h2o_rf, test_coords_ct, pos_label =1)
rf_DFauc_ct201319_h2o <- data.frame(test_data_ct$X, test_presence_ct, rf_test_pred_ct201319_h2o)
rf_auc_ct201319_h2o <- PresenceAbsence ::auc(rf_DFauc_ct201319_h2o, which.model = TRUE, na.rm=TRUE)

#rf
ct201319_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct201319_rf.tif")
rf_test_pred_ct201319<- extract(ct201319_rf, test_coords_ct, pos_label =1)
rf_DFauc_ct201319 <- data.frame(test_data_ct$X, test_presence_ct, rf_test_pred_ct201319)
rf_auc_ct201319 <- PresenceAbsence ::auc(rf_DFauc_ct201319, which.model = TRUE, na.rm=TRUE)


##**AUC Dataframe**
auc_ct_201319_h2o <- rbind(glm_auc_ct201319_h2o, rf_auc_ct201319_h2o)
colnames(auc_ct_201319_h2o) <- c("AUC", "StdDev")
rownames(auc_ct_201319_h2o) <-c("GLM", "Rf")

auc_ct_201319 <- rbind(glm_auc_ct201319, rf_auc_ct201319)
colnames(auc_ct_201319) <- c("AUC", "StdDev")
rownames(auc_ct_201319) <-c("GLM", "Rf")

write.csv(auc_ct_201319_h2o, "C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_201319_h2o.csv")
write.csv(auc_ct_201319, "C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_201319.csv")



#**YW201332**
#glm_h20
ct201332_h2o_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct201332_h2o_glm.tif")
glm_test_pred_ct201332_h2o <- extract(ct201332_h2o_glm, test_coords_ct, pos_label =1)
glm_DFauc_ct201332_h2o <- data.frame(test_data_ct$X, test_presence_ct, glm_test_pred_ct201332_h2o)
glm_auc_ct201332_h2o <- PresenceAbsence ::auc(glm_DFauc_ct201332_h2o, which.model = TRUE, na.rm=TRUE)

#glm
ct201332_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct201332_glm.tif")
glm_test_pred_ct201332<- extract(ct201332_glm, test_coords_ct, pos_label =1)
glm_DFauc_ct201332 <- data.frame(test_data_ct$X, test_presence_ct, glm_test_pred_ct201332)
glm_auc_ct201332 <- PresenceAbsence ::auc(glm_DFauc_ct201332, which.model = TRUE, na.rm=TRUE)

#rf_h20
ct201332_h2o_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct201332_h2o_rf.tif")
rf_test_pred_ct201332_h2o <- extract(ct201332_h2o_rf, test_coords_ct, pos_label =1)
rf_DFauc_ct201332_h2o <- data.frame(test_data_ct$X, test_presence_ct, rf_test_pred_ct201332_h2o)
rf_auc_ct201332_h2o <- PresenceAbsence ::auc(rf_DFauc_ct201332_h2o, which.model = TRUE, na.rm=TRUE)

#rf
ct201332_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct201332_rf.tif")
rf_test_pred_ct201332<- extract(ct201332_rf, test_coords_ct, pos_label =1)
rf_DFauc_ct201332 <- data.frame(test_data_ct$X, test_presence_ct, rf_test_pred_ct201332)
rf_auc_ct201332 <- PresenceAbsence ::auc(rf_DFauc_ct201332, which.model = TRUE, na.rm=TRUE)


##**AUC Dataframe**
auc_ct_201332_h2o <- rbind(glm_auc_ct201332_h2o, rf_auc_ct201332_h2o)
colnames(auc_ct_201332_h2o) <- c("AUC", "StdDev")
rownames(auc_ct_201332_h2o) <-c("GLM", "Rf")

auc_ct_201332 <- rbind(glm_auc_ct201332, rf_auc_ct201332)
colnames(auc_ct_201332) <- c("AUC", "StdDev")
rownames(auc_ct_201332) <-c("GLM", "Rf")

write.csv(auc_ct_201332_h2o, "C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_201332_h2o.csv")
write.csv(auc_ct_201332, "C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_201332.csv")



#**YW201345**
#glm_h20
ct201345_h2o_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct201345_h2o_glm.tif")
glm_test_pred_ct201345_h2o <- extract(ct201345_h2o_glm, test_coords_ct, pos_label =1)
glm_DFauc_ct201345_h2o <- data.frame(test_data_ct$X, test_presence_ct, glm_test_pred_ct201345_h2o)
glm_auc_ct201345_h2o <- PresenceAbsence ::auc(glm_DFauc_ct201345_h2o, which.model = TRUE, na.rm=TRUE)

#glm
ct201345_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct201345_glm.tif")
glm_test_pred_ct201345<- extract(ct201345_glm, test_coords_ct, pos_label =1)
glm_DFauc_ct201345 <- data.frame(test_data_ct$X, test_presence_ct, glm_test_pred_ct201345)
glm_auc_ct201345 <- PresenceAbsence ::auc(glm_DFauc_ct201345, which.model = TRUE, na.rm=TRUE)

#rf_h20
ct201345_h2o_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct201345_h2o_rf.tif")
rf_test_pred_ct201345_h2o <- extract(ct201345_h2o_rf, test_coords_ct, pos_label =1)
rf_DFauc_ct201345_h2o <- data.frame(test_data_ct$X, test_presence_ct, rf_test_pred_ct201345_h2o)
rf_auc_ct201345_h2o <- PresenceAbsence ::auc(rf_DFauc_ct201345_h2o, which.model = TRUE, na.rm=TRUE)

#rf
ct201345_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct201345_rf.tif")
rf_test_pred_ct201345<- extract(ct201345_rf, test_coords_ct, pos_label =1)
rf_DFauc_ct201345 <- data.frame(test_data_ct$X, test_presence_ct, rf_test_pred_ct201345)
rf_auc_ct201345 <- PresenceAbsence ::auc(rf_DFauc_ct201345, which.model = TRUE, na.rm=TRUE)


##**AUC Dataframe**
auc_ct_201345_h2o <- rbind(glm_auc_ct201345_h2o, rf_auc_ct201345_h2o)
colnames(auc_ct_201345_h2o) <- c("AUC", "StdDev")
rownames(auc_ct_201345_h2o) <-c("GLM", "Rf")

auc_ct_201345 <- rbind(glm_auc_ct201345, rf_auc_ct201345)
colnames(auc_ct_201345) <- c("AUC", "StdDev")
rownames(auc_ct_201345) <-c("GLM", "Rf")

write.csv(auc_ct_201345_h2o, "C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_201345_h2o.csv")
write.csv(auc_ct_201345, "C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_201345.csv")






#**YW201919**
#glm_h20
ct201919_h2o_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct201919_h2o_glm.tif")
glm_test_pred_ct201919_h2o <- extract(ct201919_h2o_glm, test_coords_ct, pos_label =1)
glm_DFauc_ct201919_h2o <- data.frame(test_data_ct$X, test_presence_ct, glm_test_pred_ct201919_h2o)
glm_auc_ct201919_h2o <- PresenceAbsence ::auc(glm_DFauc_ct201919_h2o, which.model = TRUE, na.rm=TRUE)

#glm
ct201919_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct201919_glm.tif")
glm_test_pred_ct201919<- extract(ct201919_glm, test_coords_ct, pos_label =1)
glm_DFauc_ct201919 <- data.frame(test_data_ct$X, test_presence_ct, glm_test_pred_ct201919)
glm_auc_ct201919 <- PresenceAbsence ::auc(glm_DFauc_ct201919, which.model = TRUE, na.rm=TRUE)

#rf_h20
ct201919_h2o_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct201919_h2o_rf.tif")
rf_test_pred_ct201919_h2o <- extract(ct201919_h2o_rf, test_coords_ct, pos_label =1)
rf_DFauc_ct201919_h2o <- data.frame(test_data_ct$X, test_presence_ct, rf_test_pred_ct201919_h2o)
rf_auc_ct201919_h2o <- PresenceAbsence ::auc(rf_DFauc_ct201919_h2o, which.model = TRUE, na.rm=TRUE)

#rf
ct201919_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct201919_rf.tif")
rf_test_pred_ct201919<- extract(ct201919_rf, test_coords_ct, pos_label =1)
rf_DFauc_ct201919 <- data.frame(test_data_ct$X, test_presence_ct, rf_test_pred_ct201919)
rf_auc_ct201919 <- PresenceAbsence ::auc(rf_DFauc_ct201919, which.model = TRUE, na.rm=TRUE)


##**AUC Dataframe**
auc_ct_201919_h2o <- rbind(glm_auc_ct201919_h2o, rf_auc_ct201919_h2o)
colnames(auc_ct_201919_h2o) <- c("AUC", "StdDev")
rownames(auc_ct_201919_h2o) <-c("GLM", "Rf")

auc_ct_201919 <- rbind(glm_auc_ct201919, rf_auc_ct201919)
colnames(auc_ct_201919) <- c("AUC", "StdDev")
rownames(auc_ct_201919) <-c("GLM", "Rf")

write.csv(auc_ct_201919_h2o, "C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_201919_h2o.csv")
write.csv(auc_ct_201919, "C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_201919.csv")



#**YW201932**
#glm_h20
ct201932_h2o_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct201932_h2o_glm.tif")
glm_test_pred_ct201932_h2o <- extract(ct201932_h2o_glm, test_coords_ct, pos_label =1)
glm_DFauc_ct201932_h2o <- data.frame(test_data_ct$X, test_presence_ct, glm_test_pred_ct201932_h2o)
glm_auc_ct201932_h2o <- PresenceAbsence ::auc(glm_DFauc_ct201932_h2o, which.model = TRUE, na.rm=TRUE)

#glm
ct201932_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct201932_glm.tif")
glm_test_pred_ct201932<- extract(ct201932_glm, test_coords_ct, pos_label =1)
glm_DFauc_ct201932 <- data.frame(test_data_ct$X, test_presence_ct, glm_test_pred_ct201932)
glm_auc_ct201932 <- PresenceAbsence ::auc(glm_DFauc_ct201932, which.model = TRUE, na.rm=TRUE)

#rf_h20
ct201932_h2o_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct201932_h2o_rf.tif")
rf_test_pred_ct201932_h2o <- extract(ct201932_h2o_rf, test_coords_ct, pos_label =1)
rf_DFauc_ct201932_h2o <- data.frame(test_data_ct$X, test_presence_ct, rf_test_pred_ct201932_h2o)
rf_auc_ct201932_h2o <- PresenceAbsence ::auc(rf_DFauc_ct201932_h2o, which.model = TRUE, na.rm=TRUE)

#rf
ct201932_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct201932_rf.tif")
rf_test_pred_ct201932<- extract(ct201932_rf, test_coords_ct, pos_label =1)
rf_DFauc_ct201932 <- data.frame(test_data_ct$X, test_presence_ct, rf_test_pred_ct201932)
rf_auc_ct201932 <- PresenceAbsence ::auc(rf_DFauc_ct201932, which.model = TRUE, na.rm=TRUE)


##**AUC Dataframe**
auc_ct_201932_h2o <- rbind(glm_auc_ct201932_h2o, rf_auc_ct201932_h2o)
colnames(auc_ct_201932_h2o) <- c("AUC", "StdDev")
rownames(auc_ct_201932_h2o) <-c("GLM", "Rf")

auc_ct_201932 <- rbind(glm_auc_ct201932, rf_auc_ct201932)
colnames(auc_ct_201932) <- c("AUC", "StdDev")
rownames(auc_ct_201932) <-c("GLM", "Rf")

write.csv(auc_ct_201932_h2o, "C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_201932_h2o.csv")
write.csv(auc_ct_201932, "C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_201932.csv")



#**YW201945**
#glm_h20
ct201945_h2o_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct201945_h2o_glm.tif")
glm_test_pred_ct201945_h2o <- extract(ct201945_h2o_glm, test_coords_ct, pos_label =1)
glm_DFauc_ct201945_h2o <- data.frame(test_data_ct$X, test_presence_ct, glm_test_pred_ct201945_h2o)
glm_auc_ct201945_h2o <- PresenceAbsence ::auc(glm_DFauc_ct201945_h2o, which.model = TRUE, na.rm=TRUE)

#glm
ct201945_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct201945_glm.tif")
glm_test_pred_ct201945<- extract(ct201945_glm, test_coords_ct, pos_label =1)
glm_DFauc_ct201945 <- data.frame(test_data_ct$X, test_presence_ct, glm_test_pred_ct201945)
glm_auc_ct201945 <- PresenceAbsence ::auc(glm_DFauc_ct201945, which.model = TRUE, na.rm=TRUE)

#rf_h20
ct201945_h2o_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct201945_h2o_rf.tif")
rf_test_pred_ct201945_h2o <- extract(ct201945_h2o_rf, test_coords_ct, pos_label =1)
rf_DFauc_ct201945_h2o <- data.frame(test_data_ct$X, test_presence_ct, rf_test_pred_ct201945_h2o)
rf_auc_ct201945_h2o <- PresenceAbsence ::auc(rf_DFauc_ct201945_h2o, which.model = TRUE, na.rm=TRUE)

#rf
ct201945_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct201945_rf.tif")
rf_test_pred_ct201945<- extract(ct201945_rf, test_coords_ct, pos_label =1)
rf_DFauc_ct201945 <- data.frame(test_data_ct$X, test_presence_ct, rf_test_pred_ct201945)
rf_auc_ct201945 <- PresenceAbsence ::auc(rf_DFauc_ct201945, which.model = TRUE, na.rm=TRUE)


##**AUC Dataframe**
auc_ct_201945_h2o <- rbind(glm_auc_ct201945_h2o, rf_auc_ct201945_h2o)
colnames(auc_ct_201945_h2o) <- c("AUC", "StdDev")
rownames(auc_ct_201945_h2o) <-c("GLM", "Rf")

auc_ct_201945 <- rbind(glm_auc_ct201945, rf_auc_ct201945)
colnames(auc_ct_201945) <- c("AUC", "StdDev")
rownames(auc_ct_201945) <-c("GLM", "Rf")

write.csv(auc_ct_201945_h2o, "C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_201945_h2o.csv")
write.csv(auc_ct_201945, "C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_201945.csv")



#**YW202119**
#glm_h20
ct202119_h2o_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct202119_h2o_glm.tif")
glm_test_pred_ct202119_h2o <- extract(ct202119_h2o_glm, test_coords_ct, pos_label =1)
glm_DFauc_ct202119_h2o <- data.frame(test_data_ct$X, test_presence_ct, glm_test_pred_ct202119_h2o)
glm_auc_ct202119_h2o <- PresenceAbsence ::auc(glm_DFauc_ct202119_h2o, which.model = TRUE, na.rm=TRUE)

#glm
ct202119_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct202119_glm.tif")
glm_test_pred_ct202119<- extract(ct202119_glm, test_coords_ct, pos_label =1)
glm_DFauc_ct202119 <- data.frame(test_data_ct$X, test_presence_ct, glm_test_pred_ct202119)
glm_auc_ct202119 <- PresenceAbsence ::auc(glm_DFauc_ct202119, which.model = TRUE, na.rm=TRUE)

#rf_h20
ct202119_h2o_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct202119_h2o_rf.tif")
rf_test_pred_ct202119_h2o <- extract(ct202119_h2o_rf, test_coords_ct, pos_label =1)
rf_DFauc_ct202119_h2o <- data.frame(test_data_ct$X, test_presence_ct, rf_test_pred_ct202119_h2o)
rf_auc_ct202119_h2o <- PresenceAbsence ::auc(rf_DFauc_ct202119_h2o, which.model = TRUE, na.rm=TRUE)

#rf
ct202119_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct202119_rf.tif")
rf_test_pred_ct202119<- extract(ct202119_rf, test_coords_ct, pos_label =1)
rf_DFauc_ct202119 <- data.frame(test_data_ct$X, test_presence_ct, rf_test_pred_ct202119)
rf_auc_ct202119 <- PresenceAbsence ::auc(rf_DFauc_ct202119, which.model = TRUE, na.rm=TRUE)


##**AUC Dataframe**
auc_ct_202119_h2o <- rbind(glm_auc_ct202119_h2o, rf_auc_ct202119_h2o)
colnames(auc_ct_202119_h2o) <- c("AUC", "StdDev")
rownames(auc_ct_202119_h2o) <-c("GLM", "Rf")

auc_ct_202119 <- rbind(glm_auc_ct202119, rf_auc_ct202119)
colnames(auc_ct_202119) <- c("AUC", "StdDev")
rownames(auc_ct_202119) <-c("GLM", "Rf")

write.csv(auc_ct_202119_h2o, "C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_202119_h2o.csv")
write.csv(auc_ct_202119, "C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_202119.csv")



#**YW202132**
#glm_h20
ct202132_h2o_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct202132_h2o_glm.tif")
glm_test_pred_ct202132_h2o <- extract(ct202132_h2o_glm, test_coords_ct, pos_label =1)
glm_DFauc_ct202132_h2o <- data.frame(test_data_ct$X, test_presence_ct, glm_test_pred_ct202132_h2o)
glm_auc_ct202132_h2o <- PresenceAbsence ::auc(glm_DFauc_ct202132_h2o, which.model = TRUE, na.rm=TRUE)

#glm
ct202132_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct202132_glm.tif")
glm_test_pred_ct202132<- extract(ct202132_glm, test_coords_ct, pos_label =1)
glm_DFauc_ct202132 <- data.frame(test_data_ct$X, test_presence_ct, glm_test_pred_ct202132)
glm_auc_ct202132 <- PresenceAbsence ::auc(glm_DFauc_ct202132, which.model = TRUE, na.rm=TRUE)

#rf_h20
ct202132_h2o_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct202132_h2o_rf.tif")
rf_test_pred_ct202132_h2o <- extract(ct202132_h2o_rf, test_coords_ct, pos_label =1)
rf_DFauc_ct202132_h2o <- data.frame(test_data_ct$X, test_presence_ct, rf_test_pred_ct202132_h2o)
rf_auc_ct202132_h2o <- PresenceAbsence ::auc(rf_DFauc_ct202132_h2o, which.model = TRUE, na.rm=TRUE)

#rf
ct202132_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct202132_rf.tif")
rf_test_pred_ct202132<- extract(ct202132_rf, test_coords_ct, pos_label =1)
rf_DFauc_ct202132 <- data.frame(test_data_ct$X, test_presence_ct, rf_test_pred_ct202132)
rf_auc_ct202132 <- PresenceAbsence ::auc(rf_DFauc_ct202132, which.model = TRUE, na.rm=TRUE)


##**AUC Dataframe**
auc_ct_202132_h2o <- rbind(glm_auc_ct202132_h2o, rf_auc_ct202132_h2o)
colnames(auc_ct_202132_h2o) <- c("AUC", "StdDev")
rownames(auc_ct_202132_h2o) <-c("GLM", "Rf")

auc_ct_202132 <- rbind(glm_auc_ct202132, rf_auc_ct202132)
colnames(auc_ct_202132) <- c("AUC", "StdDev")
rownames(auc_ct_202132) <-c("GLM", "Rf")

write.csv(auc_ct_202132_h2o, "C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_202132_h2o.csv")
write.csv(auc_ct_202132, "C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_202132.csv")



#**YW202145**
#glm_h20
ct202145_h2o_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct202145_h2o_glm.tif")
glm_test_pred_ct202145_h2o <- extract(ct202145_h2o_glm, test_coords_ct, pos_label =1)
glm_DFauc_ct202145_h2o <- data.frame(test_data_ct$X, test_presence_ct, glm_test_pred_ct202145_h2o)
glm_auc_ct202145_h2o <- PresenceAbsence ::auc(glm_DFauc_ct202145_h2o, which.model = TRUE, na.rm=TRUE)

#glm
ct202145_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct202145_glm.tif")
glm_test_pred_ct202145<- extract(ct202145_glm, test_coords_ct, pos_label =1)
glm_DFauc_ct202145 <- data.frame(test_data_ct$X, test_presence_ct, glm_test_pred_ct202145)
glm_auc_ct202145 <- PresenceAbsence ::auc(glm_DFauc_ct202145, which.model = TRUE, na.rm=TRUE)

#rf_h20
ct202145_h2o_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct202145_h2o_rf.tif")
rf_test_pred_ct202145_h2o <- extract(ct202145_h2o_rf, test_coords_ct, pos_label =1)
rf_DFauc_ct202145_h2o <- data.frame(test_data_ct$X, test_presence_ct, rf_test_pred_ct202145_h2o)
rf_auc_ct202145_h2o <- PresenceAbsence ::auc(rf_DFauc_ct202145_h2o, which.model = TRUE, na.rm=TRUE)

#rf
ct202145_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/ct202145_rf.tif")
rf_test_pred_ct202145<- extract(ct202145_rf, test_coords_ct, pos_label =1)
rf_DFauc_ct202145 <- data.frame(test_data_ct$X, test_presence_ct, rf_test_pred_ct202145)
rf_auc_ct202145 <- PresenceAbsence ::auc(rf_DFauc_ct202145, which.model = TRUE, na.rm=TRUE)


##**AUC Dataframe**
auc_ct_202145_h2o <- rbind(glm_auc_ct202145_h2o, rf_auc_ct202145_h2o)
colnames(auc_ct_202145_h2o) <- c("AUC", "StdDev")
rownames(auc_ct_202145_h2o) <-c("GLM", "Rf")

auc_ct_202145 <- rbind(glm_auc_ct202145, rf_auc_ct202145)
colnames(auc_ct_202145) <- c("AUC", "StdDev")
rownames(auc_ct_202145) <-c("GLM", "Rf")

write.csv(auc_ct_202145_h2o, "C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_202145_h2o.csv")
write.csv(auc_ct_202145, "C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_202145.csv")



```

AUC aa
```{r}
#**aa**
train_data_aa <- read.csv(here("Natalie/data_cleaned/test_train/train_data_aa.csv"))
test_data_aa <- read.csv(here("Natalie/data_cleaned/test_train/test_data_aa.csv"))
test_coords_aa <- test_data_aa[, c("Longitude", "Latitude")]
test_presence_aa <- as.numeric(test_data_aa$aa)

#**YW201319**
#glm_h20
aa201319_h2o_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa201319_h2o_glm.tif")
glm_test_pred_aa201319_h2o <- extract(aa201319_h2o_glm, test_coords_aa, pos_label =1)
glm_DFauc_aa201319_h2o <- data.frame(test_data_aa$X, test_presence_aa, glm_test_pred_aa201319_h2o)
glm_auc_aa201319_h2o <- PresenceAbsence ::auc(glm_DFauc_aa201319_h2o, which.model = TRUE, na.rm=TRUE)

#glm
aa201319_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa201319_glm.tif")
glm_test_pred_aa201319<- extract(aa201319_glm, test_coords_aa, pos_label =1)
glm_DFauc_aa201319 <- data.frame(test_data_aa$X, test_presence_aa, glm_test_pred_aa201319)
glm_auc_aa201319 <- PresenceAbsence ::auc(glm_DFauc_aa201319, which.model = TRUE, na.rm=TRUE)

#rf_h20
aa201319_h2o_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa201319_h2o_rf.tif")
rf_test_pred_aa201319_h2o <- extract(aa201319_h2o_rf, test_coords_aa, pos_label =1)
rf_DFauc_aa201319_h2o <- data.frame(test_data_aa$X, test_presence_aa, rf_test_pred_aa201319_h2o)
rf_auc_aa201319_h2o <- PresenceAbsence ::auc(rf_DFauc_aa201319_h2o, which.model = TRUE, na.rm=TRUE)

#rf
aa201319_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa201319_rf.tif")
rf_test_pred_aa201319<- extract(aa201319_rf, test_coords_aa, pos_label =1)
rf_DFauc_aa201319 <- data.frame(test_data_aa$X, test_presence_aa, rf_test_pred_aa201319)
rf_auc_aa201319 <- PresenceAbsence ::auc(rf_DFauc_aa201319, which.model = TRUE, na.rm=TRUE)


##**AUC Dataframe**
auc_aa_201319_h2o <- rbind(glm_auc_aa201319_h2o, rf_auc_aa201319_h2o)
colnames(auc_aa_201319_h2o) <- c("AUC", "StdDev")
rownames(auc_aa_201319_h2o) <-c("GLM", "Rf")

auc_aa_201319 <- rbind(glm_auc_aa201319, rf_auc_aa201319)
colnames(auc_aa_201319) <- c("AUC", "StdDev")
rownames(auc_aa_201319) <-c("GLM", "Rf")

write.csv(auc_aa_201319_h2o, "C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_201319_h2o.csv")
write.csv(auc_aa_201319, "C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_201319.csv")



#**YW201332**
#glm_h20
aa201332_h2o_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa201332_h2o_glm.tif")
glm_test_pred_aa201332_h2o <- extract(aa201332_h2o_glm, test_coords_aa, pos_label =1)
glm_DFauc_aa201332_h2o <- data.frame(test_data_aa$X, test_presence_aa, glm_test_pred_aa201332_h2o)
glm_auc_aa201332_h2o <- PresenceAbsence ::auc(glm_DFauc_aa201332_h2o, which.model = TRUE, na.rm=TRUE)

#glm
aa201332_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa201332_glm.tif")
glm_test_pred_aa201332<- extract(aa201332_glm, test_coords_aa, pos_label =1)
glm_DFauc_aa201332 <- data.frame(test_data_aa$X, test_presence_aa, glm_test_pred_aa201332)
glm_auc_aa201332 <- PresenceAbsence ::auc(glm_DFauc_aa201332, which.model = TRUE, na.rm=TRUE)

#rf_h20
aa201332_h2o_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa201332_h2o_rf.tif")
rf_test_pred_aa201332_h2o <- extract(aa201332_h2o_rf, test_coords_aa, pos_label =1)
rf_DFauc_aa201332_h2o <- data.frame(test_data_aa$X, test_presence_aa, rf_test_pred_aa201332_h2o)
rf_auc_aa201332_h2o <- PresenceAbsence ::auc(rf_DFauc_aa201332_h2o, which.model = TRUE, na.rm=TRUE)

#rf
aa201332_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa201332_rf.tif")
rf_test_pred_aa201332<- extract(aa201332_rf, test_coords_aa, pos_label =1)
rf_DFauc_aa201332 <- data.frame(test_data_aa$X, test_presence_aa, rf_test_pred_aa201332)
rf_auc_aa201332 <- PresenceAbsence ::auc(rf_DFauc_aa201332, which.model = TRUE, na.rm=TRUE)


##**AUC Dataframe**
auc_aa_201332_h2o <- rbind(glm_auc_aa201332_h2o, rf_auc_aa201332_h2o)
colnames(auc_aa_201332_h2o) <- c("AUC", "StdDev")
rownames(auc_aa_201332_h2o) <-c("GLM", "Rf")

auc_aa_201332 <- rbind(glm_auc_aa201332, rf_auc_aa201332)
colnames(auc_aa_201332) <- c("AUC", "StdDev")
rownames(auc_aa_201332) <-c("GLM", "Rf")

write.csv(auc_aa_201332_h2o, "C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_201332_h2o.csv")
write.csv(auc_aa_201332, "C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_201332.csv")



#**YW201345**
#glm_h20
aa201345_h2o_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa201345_h2o_glm.tif")
glm_test_pred_aa201345_h2o <- extract(aa201345_h2o_glm, test_coords_aa, pos_label =1)
glm_DFauc_aa201345_h2o <- data.frame(test_data_aa$X, test_presence_aa, glm_test_pred_aa201345_h2o)
glm_auc_aa201345_h2o <- PresenceAbsence ::auc(glm_DFauc_aa201345_h2o, which.model = TRUE, na.rm=TRUE)

#glm
aa201345_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa201345_glm.tif")
glm_test_pred_aa201345<- extract(aa201345_glm, test_coords_aa, pos_label =1)
glm_DFauc_aa201345 <- data.frame(test_data_aa$X, test_presence_aa, glm_test_pred_aa201345)
glm_auc_aa201345 <- PresenceAbsence ::auc(glm_DFauc_aa201345, which.model = TRUE, na.rm=TRUE)

#rf_h20
aa201345_h2o_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa201345_h2o_rf.tif")
rf_test_pred_aa201345_h2o <- extract(aa201345_h2o_rf, test_coords_aa, pos_label =1)
rf_DFauc_aa201345_h2o <- data.frame(test_data_aa$X, test_presence_aa, rf_test_pred_aa201345_h2o)
rf_auc_aa201345_h2o <- PresenceAbsence ::auc(rf_DFauc_aa201345_h2o, which.model = TRUE, na.rm=TRUE)

#rf
aa201345_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa201345_rf.tif")
rf_test_pred_aa201345<- extract(aa201345_rf, test_coords_aa, pos_label =1)
rf_DFauc_aa201345 <- data.frame(test_data_aa$X, test_presence_aa, rf_test_pred_aa201345)
rf_auc_aa201345 <- PresenceAbsence ::auc(rf_DFauc_aa201345, which.model = TRUE, na.rm=TRUE)


##**AUC Dataframe**
auc_aa_201345_h2o <- rbind(glm_auc_aa201345_h2o, rf_auc_aa201345_h2o)
colnames(auc_aa_201345_h2o) <- c("AUC", "StdDev")
rownames(auc_aa_201345_h2o) <-c("GLM", "Rf")

auc_aa_201345 <- rbind(glm_auc_aa201345, rf_auc_aa201345)
colnames(auc_aa_201345) <- c("AUC", "StdDev")
rownames(auc_aa_201345) <-c("GLM", "Rf")

write.csv(auc_aa_201345_h2o, "C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_201345_h2o.csv")
write.csv(auc_aa_201345, "C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_201345.csv")


#**YW201919**
#glm_h20
aa201919_h2o_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa201919_h2o_glm.tif")
glm_test_pred_aa201919_h2o <- extract(aa201919_h2o_glm, test_coords_aa, pos_label =1)
glm_DFauc_aa201919_h2o <- data.frame(test_data_aa$X, test_presence_aa, glm_test_pred_aa201919_h2o)
glm_auc_aa201919_h2o <- PresenceAbsence ::auc(glm_DFauc_aa201919_h2o, which.model = TRUE, na.rm=TRUE)

#glm
aa201919_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa201919_glm.tif")
glm_test_pred_aa201919<- extract(aa201919_glm, test_coords_aa, pos_label =1)
glm_DFauc_aa201919 <- data.frame(test_data_aa$X, test_presence_aa, glm_test_pred_aa201919)
glm_auc_aa201919 <- PresenceAbsence ::auc(glm_DFauc_aa201919, which.model = TRUE, na.rm=TRUE)

#rf_h20
aa201919_h2o_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa201919_h2o_rf.tif")
rf_test_pred_aa201919_h2o <- extract(aa201919_h2o_rf, test_coords_aa, pos_label =1)
rf_DFauc_aa201919_h2o <- data.frame(test_data_aa$X, test_presence_aa, rf_test_pred_aa201919_h2o)
rf_auc_aa201919_h2o <- PresenceAbsence ::auc(rf_DFauc_aa201919_h2o, which.model = TRUE, na.rm=TRUE)

#rf
aa201919_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa201919_rf.tif")
rf_test_pred_aa201919<- extract(aa201919_rf, test_coords_aa, pos_label =1)
rf_DFauc_aa201919 <- data.frame(test_data_aa$X, test_presence_aa, rf_test_pred_aa201919)
rf_auc_aa201919 <- PresenceAbsence ::auc(rf_DFauc_aa201919, which.model = TRUE, na.rm=TRUE)


##**AUC Dataframe**
auc_aa_201919_h2o <- rbind(glm_auc_aa201919_h2o, rf_auc_aa201919_h2o)
colnames(auc_aa_201919_h2o) <- c("AUC", "StdDev")
rownames(auc_aa_201919_h2o) <-c("GLM", "Rf")

auc_aa_201919 <- rbind(glm_auc_aa201919, rf_auc_aa201919)
colnames(auc_aa_201919) <- c("AUC", "StdDev")
rownames(auc_aa_201919) <-c("GLM", "Rf")

write.csv(auc_aa_201919_h2o, "C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_201919_h2o.csv")
write.csv(auc_aa_201919, "C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_201919.csv")



#**YW201932**
#glm_h20
aa201932_h2o_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa201932_h2o_glm.tif")
glm_test_pred_aa201932_h2o <- extract(aa201932_h2o_glm, test_coords_aa, pos_label =1)
glm_DFauc_aa201932_h2o <- data.frame(test_data_aa$X, test_presence_aa, glm_test_pred_aa201932_h2o)
glm_auc_aa201932_h2o <- PresenceAbsence ::auc(glm_DFauc_aa201932_h2o, which.model = TRUE, na.rm=TRUE)

#glm
aa201932_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa201932_glm.tif")
glm_test_pred_aa201932<- extract(aa201932_glm, test_coords_aa, pos_label =1)
glm_DFauc_aa201932 <- data.frame(test_data_aa$X, test_presence_aa, glm_test_pred_aa201932)
glm_auc_aa201932 <- PresenceAbsence ::auc(glm_DFauc_aa201932, which.model = TRUE, na.rm=TRUE)

#rf_h20
aa201932_h2o_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa201932_h2o_rf.tif")
rf_test_pred_aa201932_h2o <- extract(aa201932_h2o_rf, test_coords_aa, pos_label =1)
rf_DFauc_aa201932_h2o <- data.frame(test_data_aa$X, test_presence_aa, rf_test_pred_aa201932_h2o)
rf_auc_aa201932_h2o <- PresenceAbsence ::auc(rf_DFauc_aa201932_h2o, which.model = TRUE, na.rm=TRUE)

#rf
aa201932_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa201932_rf.tif")
rf_test_pred_aa201932<- extract(aa201932_rf, test_coords_aa, pos_label =1)
rf_DFauc_aa201932 <- data.frame(test_data_aa$X, test_presence_aa, rf_test_pred_aa201932)
rf_auc_aa201932 <- PresenceAbsence ::auc(rf_DFauc_aa201932, which.model = TRUE, na.rm=TRUE)


##**AUC Dataframe**
auc_aa_201932_h2o <- rbind(glm_auc_aa201932_h2o, rf_auc_aa201932_h2o)
colnames(auc_aa_201932_h2o) <- c("AUC", "StdDev")
rownames(auc_aa_201932_h2o) <-c("GLM", "Rf")

auc_aa_201932 <- rbind(glm_auc_aa201932, rf_auc_aa201932)
colnames(auc_aa_201932) <- c("AUC", "StdDev")
rownames(auc_aa_201932) <-c("GLM", "Rf")

write.csv(auc_aa_201932_h2o, "C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_201932_h2o.csv")
write.csv(auc_aa_201932, "C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_201932.csv")



#**YW201945**
#glm_h20
aa201945_h2o_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa201945_h2o_glm.tif")
glm_test_pred_aa201945_h2o <- extract(aa201945_h2o_glm, test_coords_aa, pos_label =1)
glm_DFauc_aa201945_h2o <- data.frame(test_data_aa$X, test_presence_aa, glm_test_pred_aa201945_h2o)
glm_auc_aa201945_h2o <- PresenceAbsence ::auc(glm_DFauc_aa201945_h2o, which.model = TRUE, na.rm=TRUE)

#glm
aa201945_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa201945_glm.tif")
glm_test_pred_aa201945<- extract(aa201945_glm, test_coords_aa, pos_label =1)
glm_DFauc_aa201945 <- data.frame(test_data_aa$X, test_presence_aa, glm_test_pred_aa201945)
glm_auc_aa201945 <- PresenceAbsence ::auc(glm_DFauc_aa201945, which.model = TRUE, na.rm=TRUE)

#rf_h20
aa201945_h2o_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa201945_h2o_rf.tif")
rf_test_pred_aa201945_h2o <- extract(aa201945_h2o_rf, test_coords_aa, pos_label =1)
rf_DFauc_aa201945_h2o <- data.frame(test_data_aa$X, test_presence_aa, rf_test_pred_aa201945_h2o)
rf_auc_aa201945_h2o <- PresenceAbsence ::auc(rf_DFauc_aa201945_h2o, which.model = TRUE, na.rm=TRUE)

#rf
aa201945_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa201945_rf.tif")
rf_test_pred_aa201945<- extract(aa201945_rf, test_coords_aa, pos_label =1)
rf_DFauc_aa201945 <- data.frame(test_data_aa$X, test_presence_aa, rf_test_pred_aa201945)
rf_auc_aa201945 <- PresenceAbsence ::auc(rf_DFauc_aa201945, which.model = TRUE, na.rm=TRUE)


##**AUC Dataframe**
auc_aa_201945_h2o <- rbind(glm_auc_aa201945_h2o, rf_auc_aa201945_h2o)
colnames(auc_aa_201945_h2o) <- c("AUC", "StdDev")
rownames(auc_aa_201945_h2o) <-c("GLM", "Rf")

auc_aa_201945 <- rbind(glm_auc_aa201945, rf_auc_aa201945)
colnames(auc_aa_201945) <- c("AUC", "StdDev")
rownames(auc_aa_201945) <-c("GLM", "Rf")

write.csv(auc_aa_201945_h2o, "C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_201945_h2o.csv")
write.csv(auc_aa_201945, "C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_201945.csv")



#**YW202119**
#glm_h20
aa202119_h2o_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa202119_h2o_glm.tif")
glm_test_pred_aa202119_h2o <- extract(aa202119_h2o_glm, test_coords_aa, pos_label =1)
glm_DFauc_aa202119_h2o <- data.frame(test_data_aa$X, test_presence_aa, glm_test_pred_aa202119_h2o)
glm_auc_aa202119_h2o <- PresenceAbsence ::auc(glm_DFauc_aa202119_h2o, which.model = TRUE, na.rm=TRUE)

#glm
aa202119_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa202119_glm.tif")
glm_test_pred_aa202119<- extract(aa202119_glm, test_coords_aa, pos_label =1)
glm_DFauc_aa202119 <- data.frame(test_data_aa$X, test_presence_aa, glm_test_pred_aa202119)
glm_auc_aa202119 <- PresenceAbsence ::auc(glm_DFauc_aa202119, which.model = TRUE, na.rm=TRUE)

#rf_h20
aa202119_h2o_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa202119_h2o_rf.tif")
rf_test_pred_aa202119_h2o <- extract(aa202119_h2o_rf, test_coords_aa, pos_label =1)
rf_DFauc_aa202119_h2o <- data.frame(test_data_aa$X, test_presence_aa, rf_test_pred_aa202119_h2o)
rf_auc_aa202119_h2o <- PresenceAbsence ::auc(rf_DFauc_aa202119_h2o, which.model = TRUE, na.rm=TRUE)

#rf
aa202119_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa202119_rf.tif")
rf_test_pred_aa202119<- extract(aa202119_rf, test_coords_aa, pos_label =1)
rf_DFauc_aa202119 <- data.frame(test_data_aa$X, test_presence_aa, rf_test_pred_aa202119)
rf_auc_aa202119 <- PresenceAbsence ::auc(rf_DFauc_aa202119, which.model = TRUE, na.rm=TRUE)


##**AUC Dataframe**
auc_aa_202119_h2o <- rbind(glm_auc_aa202119_h2o, rf_auc_aa202119_h2o)
colnames(auc_aa_202119_h2o) <- c("AUC", "StdDev")
rownames(auc_aa_202119_h2o) <-c("GLM", "Rf")

auc_aa_202119 <- rbind(glm_auc_aa202119, rf_auc_aa202119)
colnames(auc_aa_202119) <- c("AUC", "StdDev")
rownames(auc_aa_202119) <-c("GLM", "Rf")

write.csv(auc_aa_202119_h2o, "C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_202119_h2o.csv")
write.csv(auc_aa_202119, "C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_202119.csv")



#**YW202132**
#glm_h20
aa202132_h2o_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa202132_h2o_glm.tif")
glm_test_pred_aa202132_h2o <- extract(aa202132_h2o_glm, test_coords_aa, pos_label =1)
glm_DFauc_aa202132_h2o <- data.frame(test_data_aa$X, test_presence_aa, glm_test_pred_aa202132_h2o)
glm_auc_aa202132_h2o <- PresenceAbsence ::auc(glm_DFauc_aa202132_h2o, which.model = TRUE, na.rm=TRUE)

#glm
aa202132_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa202132_glm.tif")
glm_test_pred_aa202132<- extract(aa202132_glm, test_coords_aa, pos_label =1)
glm_DFauc_aa202132 <- data.frame(test_data_aa$X, test_presence_aa, glm_test_pred_aa202132)
glm_auc_aa202132 <- PresenceAbsence ::auc(glm_DFauc_aa202132, which.model = TRUE, na.rm=TRUE)

#rf_h20
aa202132_h2o_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa202132_h2o_rf.tif")
rf_test_pred_aa202132_h2o <- extract(aa202132_h2o_rf, test_coords_aa, pos_label =1)
rf_DFauc_aa202132_h2o <- data.frame(test_data_aa$X, test_presence_aa, rf_test_pred_aa202132_h2o)
rf_auc_aa202132_h2o <- PresenceAbsence ::auc(rf_DFauc_aa202132_h2o, which.model = TRUE, na.rm=TRUE)

#rf
aa202132_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa202132_rf.tif")
rf_test_pred_aa202132<- extract(aa202132_rf, test_coords_aa, pos_label =1)
rf_DFauc_aa202132 <- data.frame(test_data_aa$X, test_presence_aa, rf_test_pred_aa202132)
rf_auc_aa202132 <- PresenceAbsence ::auc(rf_DFauc_aa202132, which.model = TRUE, na.rm=TRUE)


##**AUC Dataframe**
auc_aa_202132_h2o <- rbind(glm_auc_aa202132_h2o, rf_auc_aa202132_h2o)
colnames(auc_aa_202132_h2o) <- c("AUC", "StdDev")
rownames(auc_aa_202132_h2o) <-c("GLM", "Rf")

auc_aa_202132 <- rbind(glm_auc_aa202132, rf_auc_aa202132)
colnames(auc_aa_202132) <- c("AUC", "StdDev")
rownames(auc_aa_202132) <-c("GLM", "Rf")

write.csv(auc_aa_202132_h2o, "C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_202132_h2o.csv")
write.csv(auc_aa_202132, "C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_202132.csv")



#**YW202145**
#glm_h20
aa202145_h2o_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa202145_h2o_glm.tif")
glm_test_pred_aa202145_h2o <- extract(aa202145_h2o_glm, test_coords_aa, pos_label =1)
glm_DFauc_aa202145_h2o <- data.frame(test_data_aa$X, test_presence_aa, glm_test_pred_aa202145_h2o)
glm_auc_aa202145_h2o <- PresenceAbsence ::auc(glm_DFauc_aa202145_h2o, which.model = TRUE, na.rm=TRUE)

#glm
aa202145_glm <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa202145_glm.tif")
glm_test_pred_aa202145<- extract(aa202145_glm, test_coords_aa, pos_label =1)
glm_DFauc_aa202145 <- data.frame(test_data_aa$X, test_presence_aa, glm_test_pred_aa202145)
glm_auc_aa202145 <- PresenceAbsence ::auc(glm_DFauc_aa202145, which.model = TRUE, na.rm=TRUE)

#rf_h20
aa202145_h2o_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa202145_h2o_rf.tif")
rf_test_pred_aa202145_h2o <- extract(aa202145_h2o_rf, test_coords_aa, pos_label =1)
rf_DFauc_aa202145_h2o <- data.frame(test_data_aa$X, test_presence_aa, rf_test_pred_aa202145_h2o)
rf_auc_aa202145_h2o <- PresenceAbsence ::auc(rf_DFauc_aa202145_h2o, which.model = TRUE, na.rm=TRUE)

#rf
aa202145_rf <- raster("C:/Users/nooni/Box/RNR597_data/prediction/aa202145_rf.tif")
rf_test_pred_aa202145<- extract(aa202145_rf, test_coords_aa, pos_label =1)
rf_DFauc_aa202145 <- data.frame(test_data_aa$X, test_presence_aa, rf_test_pred_aa202145)
rf_auc_aa202145 <- PresenceAbsence ::auc(rf_DFauc_aa202145, which.model = TRUE, na.rm=TRUE)


##**AUC Dataframe**
auc_aa_202145_h2o <- rbind(glm_auc_aa202145_h2o, rf_auc_aa202145_h2o)
colnames(auc_aa_202145_h2o) <- c("AUC", "StdDev")
rownames(auc_aa_202145_h2o) <-c("GLM", "Rf")

auc_aa_202145 <- rbind(glm_auc_aa202145, rf_auc_aa202145)
colnames(auc_aa_202145) <- c("AUC", "StdDev")
rownames(auc_aa_202145) <-c("GLM", "Rf")

write.csv(auc_aa_202145_h2o, "C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_202145_h2o.csv")
write.csv(auc_aa_202145, "C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_202145.csv")



```


Ensemble Model -cq
```{r}

#**YW201319*
cq201319_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/cq201319_glm.tif")
cq201319_h2o_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/cq201319_h2o_glm.tif")
cq201319_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/cq201319_rf.tif")
cq201319_h2o_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/cq201319_h2o_rf.tif")
auc_cq_201319 <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_201319.csv")
auc_cq_201319_h2o <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_201319_h2o.csv")

#ensemble no water
pred_stack_cq201319 <- stack(x = c(cq201319_glm, cq201319_rf))
weights_cq201319 <- auc_cq_201319$AUC / sum(auc_cq_201319$AUC)
ensemble_pred_cq201319 <- weighted.mean(pred_stack_cq201319, w = weights_cq201319)
plot(ensemble_pred_cq201319)
writeRaster(ensemble_pred_cq201319, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_cq201319.tif")

#using test data now to get AUC 
test_data_cq <- read.csv(here("Natalie/data_cleaned/test_train/test_data_cq.csv"))
test_coords_cq <- test_data_cq[, c("Longitude", "Latitude")]
test_presence_cq <- as.numeric(test_data_cq$cq)
ensemble_test_pred_cq201319 <- extract(ensemble_pred_cq201319, test_coords_cq, pos_label = 1)
ensemble_auc_df_cq201319 <- data.frame(test_data_cq$X, test_presence_cq, ensemble_test_pred_cq201319)
auc_ensemble_cq201319<- PresenceAbsence ::auc(ensemble_auc_df_cq201319, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_cq201319, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_cq201319.csv")

#h2o
pred_stack_cq201319_h2o <- stack(x = c(cq201319_h2o_glm, cq201319_h2o_rf))
weights_cq201319_h2o <- auc_cq_201319_h2o$AUC / sum(auc_cq_201319_h2o$AUC)

ensemble_pred_cq201319_h2o <- weighted.mean(pred_stack_cq201319_h2o, w = weights_cq201319_h2o)
plot(ensemble_pred_cq201319_h2o)
writeRaster(ensemble_pred_cq201319_h2o, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_cq201319_h2o.tif")

#using test data now to get AUC
test_data_cq <- read.csv(here("Natalie/data_cleaned/test_train/test_data_cq.csv"))
test_coords_cq <- test_data_cq[, c("Longitude", "Latitude")]
test_presence_cq <- as.numeric(test_data_cq$cq)
ensemble_test_pred_cq201319_h2o <- extract(ensemble_pred_cq201319_h2o, test_coords_cq, pos_label = 1)
ensemble_auc_df_cq201319_h2o <- data.frame(test_data_cq$X, test_presence_cq, ensemble_test_pred_cq201319_h2o)
auc_ensemble_cq201319_h2o<- PresenceAbsence ::auc(ensemble_auc_df_cq201319, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_cq201319_h2o, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_cq201319_h2o.csv")

#**YW201332*
cq201332_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/cq201332_glm.tif")
cq201332_h2o_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/cq201332_h2o_glm.tif")
cq201332_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/cq201332_rf.tif")
cq201332_h2o_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/cq201332_h2o_rf.tif")
auc_cq_201332 <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_201332.csv")
auc_cq_201332_h2o <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_201332_h2o.csv")

#ensemble no water
pred_stack_cq201332 <- stack(x = c(cq201332_glm, cq201332_rf))
weights_cq201332 <- auc_cq_201332$AUC / sum(auc_cq_201332$AUC)
ensemble_pred_cq201332 <- weighted.mean(pred_stack_cq201332, w = weights_cq201332)
plot(ensemble_pred_cq201332)
writeRaster(ensemble_pred_cq201332, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_cq201332.tif")

#using test data now to get AUC 
test_data_cq <- read.csv(here("Natalie/data_cleaned/test_train/test_data_cq.csv"))
test_coords_cq <- test_data_cq[, c("Longitude", "Latitude")]
test_presence_cq <- as.numeric(test_data_cq$cq)
ensemble_test_pred_cq201332 <- extract(ensemble_pred_cq201332, test_coords_cq, pos_label = 1)
ensemble_auc_df_cq201332 <- data.frame(test_data_cq$X, test_presence_cq, ensemble_test_pred_cq201332)
auc_ensemble_cq201332<- PresenceAbsence ::auc(ensemble_auc_df_cq201332, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_cq201332, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_cq201332.csv")

#h2o
pred_stack_cq201332_h2o <- stack(x = c(cq201332_h2o_glm, cq201332_h2o_rf))
weights_cq201332_h2o <- auc_cq_201332_h2o$AUC / sum(auc_cq_201332_h2o$AUC)

ensemble_pred_cq201332_h2o <- weighted.mean(pred_stack_cq201332_h2o, w = weights_cq201332_h2o)
plot(ensemble_pred_cq201332_h2o)
writeRaster(ensemble_pred_cq201332_h2o, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_cq201332_h2o.tif")

#using test data now to get AUC
test_data_cq <- read.csv(here("Natalie/data_cleaned/test_train/test_data_cq.csv"))
test_coords_cq <- test_data_cq[, c("Longitude", "Latitude")]
test_presence_cq <- as.numeric(test_data_cq$cq)
ensemble_test_pred_cq201332_h2o <- extract(ensemble_pred_cq201332_h2o, test_coords_cq, pos_label = 1)
ensemble_auc_df_cq201332_h2o <- data.frame(test_data_cq$X, test_presence_cq, ensemble_test_pred_cq201332_h2o)
auc_ensemble_cq201332_h2o<- PresenceAbsence ::auc(ensemble_auc_df_cq201332, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_cq201332_h2o, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_cq201332_h2o.csv")


#**YW201345*
cq201345_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/cq201345_glm.tif")
cq201345_h2o_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/cq201345_h2o_glm.tif")
cq201345_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/cq201345_rf.tif")
cq201345_h2o_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/cq201345_h2o_rf.tif")
auc_cq_201345 <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_201345.csv")
auc_cq_201345_h2o <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_201345_h2o.csv")

#ensemble no water
pred_stack_cq201345 <- stack(x = c(cq201345_glm, cq201345_rf))
weights_cq201345 <- auc_cq_201345$AUC / sum(auc_cq_201345$AUC)
ensemble_pred_cq201345 <- weighted.mean(pred_stack_cq201345, w = weights_cq201345)
plot(ensemble_pred_cq201345)
writeRaster(ensemble_pred_cq201345, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_cq201345.tif")

#using test data now to get AUC 
test_data_cq <- read.csv(here("Natalie/data_cleaned/test_train/test_data_cq.csv"))
test_coords_cq <- test_data_cq[, c("Longitude", "Latitude")]
test_presence_cq <- as.numeric(test_data_cq$cq)
ensemble_test_pred_cq201345 <- extract(ensemble_pred_cq201345, test_coords_cq, pos_label = 1)
ensemble_auc_df_cq201345 <- data.frame(test_data_cq$X, test_presence_cq, ensemble_test_pred_cq201345)
auc_ensemble_cq201345<- PresenceAbsence ::auc(ensemble_auc_df_cq201345, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_cq201345, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_cq201345.csv")

#h2o
pred_stack_cq201345_h2o <- stack(x = c(cq201345_h2o_glm, cq201345_h2o_rf))
weights_cq201345_h2o <- auc_cq_201345_h2o$AUC / sum(auc_cq_201345_h2o$AUC)

ensemble_pred_cq201345_h2o <- weighted.mean(pred_stack_cq201345_h2o, w = weights_cq201345_h2o)
plot(ensemble_pred_cq201345_h2o)
writeRaster(ensemble_pred_cq201345_h2o, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_cq201345_h2o.tif")

#using test data now to get AUC
test_data_cq <- read.csv(here("Natalie/data_cleaned/test_train/test_data_cq.csv"))
test_coords_cq <- test_data_cq[, c("Longitude", "Latitude")]
test_presence_cq <- as.numeric(test_data_cq$cq)
ensemble_test_pred_cq201345_h2o <- extract(ensemble_pred_cq201345_h2o, test_coords_cq, pos_label = 1)
ensemble_auc_df_cq201345_h2o <- data.frame(test_data_cq$X, test_presence_cq, ensemble_test_pred_cq201345_h2o)
auc_ensemble_cq201345_h2o<- PresenceAbsence ::auc(ensemble_auc_df_cq201345, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_cq201345_h2o, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_cq201345_h2o.csv")


#YW201919
cq201919_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/cq201919_glm.tif")
cq201919_h2o_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/cq201919_h2o_glm.tif")
cq201919_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/cq201919_rf.tif")
cq201919_h2o_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/cq201919_h2o_rf.tif")
auc_cq_201919 <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_201919.csv")
auc_cq_201919_h2o <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_201919_h2o.csv")

#ensemble no water
pred_stack_cq201919 <- stack(x = c(cq201919_glm, cq201919_rf))
weights_cq201919 <- auc_cq_201919$AUC / sum(auc_cq_201919$AUC)
ensemble_pred_cq201919 <- weighted.mean(pred_stack_cq201919, w = weights_cq201919)
plot(ensemble_pred_cq201919)
writeRaster(ensemble_pred_cq201919, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_cq201919.tif")

#using test data now to get AUC 
test_data_cq <- read.csv(here("Natalie/data_cleaned/test_train/test_data_cq.csv"))
test_coords_cq <- test_data_cq[, c("Longitude", "Latitude")]
test_presence_cq <- as.numeric(test_data_cq$cq)
ensemble_test_pred_cq201919 <- extract(ensemble_pred_cq201919, test_coords_cq, pos_label = 1)
ensemble_auc_df_cq201919 <- data.frame(test_data_cq$X, test_presence_cq, ensemble_test_pred_cq201919)
auc_ensemble_cq201919<- PresenceAbsence ::auc(ensemble_auc_df_cq201919, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_cq201919, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_cq201919.csv")

#h2o
pred_stack_cq201919_h2o <- stack(x = c(cq201919_h2o_glm, cq201919_h2o_rf))
weights_cq201919_h2o <- auc_cq_201919_h2o$AUC / sum(auc_cq_201919_h2o$AUC)

ensemble_pred_cq201919_h2o <- weighted.mean(pred_stack_cq201919_h2o, w = weights_cq201919_h2o)
plot(ensemble_pred_cq201919_h2o)
writeRaster(ensemble_pred_cq201919_h2o, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_cq201919_h2o.tif")

#using test data now to get AUC
test_data_cq <- read.csv(here("Natalie/data_cleaned/test_train/test_data_cq.csv"))
test_coords_cq <- test_data_cq[, c("Longitude", "Latitude")]
test_presence_cq <- as.numeric(test_data_cq$cq)
ensemble_test_pred_cq201919_h2o <- extract(ensemble_pred_cq201919_h2o, test_coords_cq, pos_label = 1)
ensemble_auc_df_cq201919_h2o <- data.frame(test_data_cq$X, test_presence_cq, ensemble_test_pred_cq201919_h2o)
auc_ensemble_cq201919_h2o<- PresenceAbsence ::auc(ensemble_auc_df_cq201919, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_cq201919_h2o, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_cq201919_h2o.csv")



#**YW201932*
cq201932_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/cq201932_glm.tif")
cq201932_h2o_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/cq201932_h2o_glm.tif")
cq201932_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/cq201932_rf.tif")
cq201932_h2o_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/cq201932_h2o_rf.tif")
auc_cq_201932 <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_201932.csv")
auc_cq_201932_h2o <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_201932_h2o.csv")

#ensemble no water
pred_stack_cq201932 <- stack(x = c(cq201932_glm, cq201932_rf))
weights_cq201932 <- auc_cq_201932$AUC / sum(auc_cq_201932$AUC)
ensemble_pred_cq201932 <- weighted.mean(pred_stack_cq201932, w = weights_cq201932)
plot(ensemble_pred_cq201932)
writeRaster(ensemble_pred_cq201932, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_cq201932.tif")

#using test data now to get AUC 
test_data_cq <- read.csv(here("Natalie/data_cleaned/test_train/test_data_cq.csv"))
test_coords_cq <- test_data_cq[, c("Longitude", "Latitude")]
test_presence_cq <- as.numeric(test_data_cq$cq)
ensemble_test_pred_cq201932 <- extract(ensemble_pred_cq201932, test_coords_cq, pos_label = 1)
ensemble_auc_df_cq201932 <- data.frame(test_data_cq$X, test_presence_cq, ensemble_test_pred_cq201932)
auc_ensemble_cq201932<- PresenceAbsence ::auc(ensemble_auc_df_cq201932, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_cq201932, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_cq201932.csv")

#h2o
pred_stack_cq201932_h2o <- stack(x = c(cq201932_h2o_glm, cq201932_h2o_rf))
weights_cq201932_h2o <- auc_cq_201932_h2o$AUC / sum(auc_cq_201932_h2o$AUC)

ensemble_pred_cq201932_h2o <- weighted.mean(pred_stack_cq201932_h2o, w = weights_cq201932_h2o)
plot(ensemble_pred_cq201932_h2o)
writeRaster(ensemble_pred_cq201932_h2o, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_cq201932_h2o.tif")

#using test data now to get AUC
test_data_cq <- read.csv(here("Natalie/data_cleaned/test_train/test_data_cq.csv"))
test_coords_cq <- test_data_cq[, c("Longitude", "Latitude")]
test_presence_cq <- as.numeric(test_data_cq$cq)
ensemble_test_pred_cq201932_h2o <- extract(ensemble_pred_cq201932_h2o, test_coords_cq, pos_label = 1)
ensemble_auc_df_cq201932_h2o <- data.frame(test_data_cq$X, test_presence_cq, ensemble_test_pred_cq201932_h2o)
auc_ensemble_cq201932_h2o<- PresenceAbsence ::auc(ensemble_auc_df_cq201932, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_cq201932_h2o, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_cq201932_h2o.csv")



#**YW201945**
cq201945_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/cq201945_glm.tif")
cq201945_h2o_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/cq201945_h2o_glm.tif")
cq201945_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/cq201945_rf.tif")
cq201945_h2o_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/cq201945_h2o_rf.tif")
auc_cq_201945 <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_201945.csv")
auc_cq_201945_h2o <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_201945_h2o.csv")

#ensemble no water
pred_stack_cq201945 <- stack(x = c(cq201945_glm, cq201945_rf))
weights_cq201945 <- auc_cq_201945$AUC / sum(auc_cq_201945$AUC)
ensemble_pred_cq201945 <- weighted.mean(pred_stack_cq201945, w = weights_cq201945)
plot(ensemble_pred_cq201945)
writeRaster(ensemble_pred_cq201945, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_cq201945.tif")

#using test data now to get AUC 
test_data_cq <- read.csv(here("Natalie/data_cleaned/test_train/test_data_cq.csv"))
test_coords_cq <- test_data_cq[, c("Longitude", "Latitude")]
test_presence_cq <- as.numeric(test_data_cq$cq)
ensemble_test_pred_cq201945 <- extract(ensemble_pred_cq201945, test_coords_cq, pos_label = 1)
ensemble_auc_df_cq201945 <- data.frame(test_data_cq$X, test_presence_cq, ensemble_test_pred_cq201945)
auc_ensemble_cq201945<- PresenceAbsence ::auc(ensemble_auc_df_cq201945, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_cq201945, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_cq201945.csv")

#h2o
pred_stack_cq201945_h2o <- stack(x = c(cq201945_h2o_glm, cq201945_h2o_rf))
weights_cq201945_h2o <- auc_cq_201945_h2o$AUC / sum(auc_cq_201945_h2o$AUC)

ensemble_pred_cq201945_h2o <- weighted.mean(pred_stack_cq201945_h2o, w = weights_cq201945_h2o)
plot(ensemble_pred_cq201945_h2o)
writeRaster(ensemble_pred_cq201945_h2o, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_cq201945_h2o.tif")

#using test data now to get AUC
test_data_cq <- read.csv(here("Natalie/data_cleaned/test_train/test_data_cq.csv"))
test_coords_cq <- test_data_cq[, c("Longitude", "Latitude")]
test_presence_cq <- as.numeric(test_data_cq$cq)
ensemble_test_pred_cq201945_h2o <- extract(ensemble_pred_cq201945_h2o, test_coords_cq, pos_label = 1)
ensemble_auc_df_cq201945_h2o <- data.frame(test_data_cq$X, test_presence_cq, ensemble_test_pred_cq201945_h2o)
auc_ensemble_cq201945_h2o<- PresenceAbsence ::auc(ensemble_auc_df_cq201945, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_cq201945_h2o, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_cq201945_h2o.csv")



#**YW202119*
cq202119_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/cq202119_glm.tif")
cq202119_h2o_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/cq202119_h2o_glm.tif")
cq202119_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/cq202119_rf.tif")
cq202119_h2o_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/cq202119_h2o_rf.tif")
auc_cq_202119 <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_202119.csv")
auc_cq_202119_h2o <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_202119_h2o.csv")

#ensemble no water
pred_stack_cq202119 <- stack(x = c(cq202119_glm, cq202119_rf))
weights_cq202119 <- auc_cq_202119$AUC / sum(auc_cq_202119$AUC)
ensemble_pred_cq202119 <- weighted.mean(pred_stack_cq202119, w = weights_cq202119)
plot(ensemble_pred_cq202119)
writeRaster(ensemble_pred_cq202119, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_cq202119.tif")

#using test data now to get AUC 
test_data_cq <- read.csv(here("Natalie/data_cleaned/test_train/test_data_cq.csv"))
test_coords_cq <- test_data_cq[, c("Longitude", "Latitude")]
test_presence_cq <- as.numeric(test_data_cq$cq)
ensemble_test_pred_cq202119 <- extract(ensemble_pred_cq202119, test_coords_cq, pos_label = 1)
ensemble_auc_df_cq202119 <- data.frame(test_data_cq$X, test_presence_cq, ensemble_test_pred_cq202119)
auc_ensemble_cq202119<- PresenceAbsence ::auc(ensemble_auc_df_cq202119, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_cq202119, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_cq202119.csv")

#h2o
pred_stack_cq202119_h2o <- stack(x = c(cq202119_h2o_glm, cq202119_h2o_rf))
weights_cq202119_h2o <- auc_cq_202119_h2o$AUC / sum(auc_cq_202119_h2o$AUC)

ensemble_pred_cq202119_h2o <- weighted.mean(pred_stack_cq202119_h2o, w = weights_cq202119_h2o)
plot(ensemble_pred_cq202119_h2o)
writeRaster(ensemble_pred_cq202119_h2o, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_cq202119_h2o.tif")

#using test data now to get AUC
test_data_cq <- read.csv(here("Natalie/data_cleaned/test_train/test_data_cq.csv"))
test_coords_cq <- test_data_cq[, c("Longitude", "Latitude")]
test_presence_cq <- as.numeric(test_data_cq$cq)
ensemble_test_pred_cq202119_h2o <- extract(ensemble_pred_cq202119_h2o, test_coords_cq, pos_label = 1)
ensemble_auc_df_cq202119_h2o <- data.frame(test_data_cq$X, test_presence_cq, ensemble_test_pred_cq202119_h2o)
auc_ensemble_cq202119_h2o<- PresenceAbsence ::auc(ensemble_auc_df_cq202119, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_cq202119_h2o, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_cq202119_h2o.csv")


#**YW202132*
cq202132_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/cq202132_glm.tif")
cq202132_h2o_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/cq202132_h2o_glm.tif")
cq202132_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/cq202132_rf.tif")
cq202132_h2o_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/cq202132_h2o_rf.tif")
auc_cq_202132 <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_202132.csv")
auc_cq_202132_h2o <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_202132_h2o.csv")

#ensemble no water
pred_stack_cq202132 <- stack(x = c(cq202132_glm, cq202132_rf))
weights_cq202132 <- auc_cq_202132$AUC / sum(auc_cq_202132$AUC)
ensemble_pred_cq202132 <- weighted.mean(pred_stack_cq202132, w = weights_cq202132)
plot(ensemble_pred_cq202132)
writeRaster(ensemble_pred_cq202132, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_cq202132.tif")

#using test data now to get AUC 
test_data_cq <- read.csv(here("Natalie/data_cleaned/test_train/test_data_cq.csv"))
test_coords_cq <- test_data_cq[, c("Longitude", "Latitude")]
test_presence_cq <- as.numeric(test_data_cq$cq)
ensemble_test_pred_cq202132 <- extract(ensemble_pred_cq202132, test_coords_cq, pos_label = 1)
ensemble_auc_df_cq202132 <- data.frame(test_data_cq$X, test_presence_cq, ensemble_test_pred_cq202132)
auc_ensemble_cq202132<- PresenceAbsence ::auc(ensemble_auc_df_cq202132, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_cq202132, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_cq202132.csv")

#h2o
pred_stack_cq202132_h2o <- stack(x = c(cq202132_h2o_glm, cq202132_h2o_rf))
weights_cq202132_h2o <- auc_cq_202132_h2o$AUC / sum(auc_cq_202132_h2o$AUC)

ensemble_pred_cq202132_h2o <- weighted.mean(pred_stack_cq202132_h2o, w = weights_cq202132_h2o)
plot(ensemble_pred_cq202132_h2o)
writeRaster(ensemble_pred_cq202132_h2o, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_cq202132_h2o.tif")

#using test data now to get AUC
test_data_cq <- read.csv(here("Natalie/data_cleaned/test_train/test_data_cq.csv"))
test_coords_cq <- test_data_cq[, c("Longitude", "Latitude")]
test_presence_cq <- as.numeric(test_data_cq$cq)
ensemble_test_pred_cq202132_h2o <- extract(ensemble_pred_cq202132_h2o, test_coords_cq, pos_label = 1)
ensemble_auc_df_cq202132_h2o <- data.frame(test_data_cq$X, test_presence_cq, ensemble_test_pred_cq202132_h2o)
auc_ensemble_cq202132_h2o<- PresenceAbsence ::auc(ensemble_auc_df_cq202132, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_cq202132_h2o, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_cq202132_h2o.csv")


#**YW202145*
cq202145_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/cq202145_glm.tif")
cq202145_h2o_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/cq202145_h2o_glm.tif")
cq202145_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/cq202145_rf.tif")
cq202145_h2o_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/cq202145_h2o_rf.tif")
auc_cq_202145 <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_202145.csv")
auc_cq_202145_h2o <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_cq_202145_h2o.csv")

#ensemble no water
pred_stack_cq202145 <- stack(x = c(cq202145_glm, cq202145_rf))
weights_cq202145 <- auc_cq_202145$AUC / sum(auc_cq_202145$AUC)
ensemble_pred_cq202145 <- weighted.mean(pred_stack_cq202145, w = weights_cq202145)
plot(ensemble_pred_cq202145)
writeRaster(ensemble_pred_cq202145, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_cq202145.tif")

#using test data now to get AUC 
test_data_cq <- read.csv(here("Natalie/data_cleaned/test_train/test_data_cq.csv"))
test_coords_cq <- test_data_cq[, c("Longitude", "Latitude")]
test_presence_cq <- as.numeric(test_data_cq$cq)
ensemble_test_pred_cq202145 <- extract(ensemble_pred_cq202145, test_coords_cq, pos_label = 1)
ensemble_auc_df_cq202145 <- data.frame(test_data_cq$X, test_presence_cq, ensemble_test_pred_cq202145)
auc_ensemble_cq202145<- PresenceAbsence ::auc(ensemble_auc_df_cq202145, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_cq202145, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_cq202145.csv")

#h2o
pred_stack_cq202145_h2o <- stack(x = c(cq202145_h2o_glm, cq202145_h2o_rf))
weights_cq202145_h2o <- auc_cq_202145_h2o$AUC / sum(auc_cq_202145_h2o$AUC)

ensemble_pred_cq202145_h2o <- weighted.mean(pred_stack_cq202145_h2o, w = weights_cq202145_h2o)
plot(ensemble_pred_cq202145_h2o)
writeRaster(ensemble_pred_cq202145_h2o, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_cq202145_h2o.tif")

#using test data now to get AUC
test_data_cq <- read.csv(here("Natalie/data_cleaned/test_train/test_data_cq.csv"))
test_coords_cq <- test_data_cq[, c("Longitude", "Latitude")]
test_presence_cq <- as.numeric(test_data_cq$cq)
ensemble_test_pred_cq202145_h2o <- extract(ensemble_pred_cq202145_h2o, test_coords_cq, pos_label = 1)
ensemble_auc_df_cq202145_h2o <- data.frame(test_data_cq$X, test_presence_cq, ensemble_test_pred_cq202145_h2o)
auc_ensemble_cq202145_h2o<- PresenceAbsence ::auc(ensemble_auc_df_cq202145, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_cq202145_h2o, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_cq202145_h2o.csv")


```


Ensemble model - ct
```{r}

#**YW201319*
ct201319_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/ct201319_glm.tif")
ct201319_h2o_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/ct201319_h2o_glm.tif")
ct201319_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/ct201319_rf.tif")
ct201319_h2o_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/ct201319_h2o_rf.tif")
auc_ct_201319 <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_201319.csv")
auc_ct_201319_h2o <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_201319_h2o.csv")

#ensemble no water
pred_stack_ct201319 <- stack(x = c(ct201319_glm, ct201319_rf))
weights_ct201319 <- auc_ct_201319$AUC / sum(auc_ct_201319$AUC)
ensemble_pred_ct201319 <- weighted.mean(pred_stack_ct201319, w = weights_ct201319)
plot(ensemble_pred_ct201319)
writeRaster(ensemble_pred_ct201319, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_ct201319.tif")

#using test data now to get AUC 
test_data_ct <- read.csv(here("Natalie/data_cleaned/test_train/test_data_ct.csv"))
test_coords_ct <- test_data_ct[, c("Longitude", "Latitude")]
test_presence_ct <- as.numeric(test_data_ct$ct)
ensemble_test_pred_ct201319 <- extract(ensemble_pred_ct201319, test_coords_ct, pos_label = 1)
ensemble_auc_df_ct201319 <- data.frame(test_data_ct$X, test_presence_ct, ensemble_test_pred_ct201319)
auc_ensemble_ct201319<- PresenceAbsence ::auc(ensemble_auc_df_ct201319, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_ct201319, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_ct201319.csv")

#h2o
pred_stack_ct201319_h2o <- stack(x = c(ct201319_h2o_glm, ct201319_h2o_rf))
weights_ct201319_h2o <- auc_ct_201319_h2o$AUC / sum(auc_ct_201319_h2o$AUC)

ensemble_pred_ct201319_h2o <- weighted.mean(pred_stack_ct201319_h2o, w = weights_ct201319_h2o)
plot(ensemble_pred_ct201319_h2o)
writeRaster(ensemble_pred_ct201319_h2o, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_ct201319_h2o.tif")

#using test data now to get AUC
test_data_ct <- read.csv(here("Natalie/data_cleaned/test_train/test_data_ct.csv"))
test_coords_ct <- test_data_ct[, c("Longitude", "Latitude")]
test_presence_ct <- as.numeric(test_data_ct$ct)
ensemble_test_pred_ct201319_h2o <- extract(ensemble_pred_ct201319_h2o, test_coords_ct, pos_label = 1)
ensemble_auc_df_ct201319_h2o <- data.frame(test_data_ct$X, test_presence_ct, ensemble_test_pred_ct201319_h2o)
auc_ensemble_ct201319_h2o<- PresenceAbsence ::auc(ensemble_auc_df_ct201319, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_ct201319_h2o, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_ct201319_h2o.csv")

#**YW201332*
ct201332_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/ct201332_glm.tif")
ct201332_h2o_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/ct201332_h2o_glm.tif")
ct201332_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/ct201332_rf.tif")
ct201332_h2o_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/ct201332_h2o_rf.tif")
auc_ct_201332 <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_201332.csv")
auc_ct_201332_h2o <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_201332_h2o.csv")

#ensemble no water
pred_stack_ct201332 <- stack(x = c(ct201332_glm, ct201332_rf))
weights_ct201332 <- auc_ct_201332$AUC / sum(auc_ct_201332$AUC)
ensemble_pred_ct201332 <- weighted.mean(pred_stack_ct201332, w = weights_ct201332)
plot(ensemble_pred_ct201332)
writeRaster(ensemble_pred_ct201332, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_ct201332.tif")

#using test data now to get AUC 
test_data_ct <- read.csv(here("Natalie/data_cleaned/test_train/test_data_ct.csv"))
test_coords_ct <- test_data_ct[, c("Longitude", "Latitude")]
test_presence_ct <- as.numeric(test_data_ct$ct)
ensemble_test_pred_ct201332 <- extract(ensemble_pred_ct201332, test_coords_ct, pos_label = 1)
ensemble_auc_df_ct201332 <- data.frame(test_data_ct$X, test_presence_ct, ensemble_test_pred_ct201332)
auc_ensemble_ct201332<- PresenceAbsence ::auc(ensemble_auc_df_ct201332, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_ct201332, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_ct201332.csv")

#h2o
pred_stack_ct201332_h2o <- stack(x = c(ct201332_h2o_glm, ct201332_h2o_rf))
weights_ct201332_h2o <- auc_ct_201332_h2o$AUC / sum(auc_ct_201332_h2o$AUC)

ensemble_pred_ct201332_h2o <- weighted.mean(pred_stack_ct201332_h2o, w = weights_ct201332_h2o)
plot(ensemble_pred_ct201332_h2o)
writeRaster(ensemble_pred_ct201332_h2o, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_ct201332_h2o.tif")

#using test data now to get AUC
test_data_ct <- read.csv(here("Natalie/data_cleaned/test_train/test_data_ct.csv"))
test_coords_ct <- test_data_ct[, c("Longitude", "Latitude")]
test_presence_ct <- as.numeric(test_data_ct$ct)
ensemble_test_pred_ct201332_h2o <- extract(ensemble_pred_ct201332_h2o, test_coords_ct, pos_label = 1)
ensemble_auc_df_ct201332_h2o <- data.frame(test_data_ct$X, test_presence_ct, ensemble_test_pred_ct201332_h2o)
auc_ensemble_ct201332_h2o<- PresenceAbsence ::auc(ensemble_auc_df_ct201332, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_ct201332_h2o, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_ct201332_h2o.csv")


#**YW201345*
ct201345_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/ct201345_glm.tif")
ct201345_h2o_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/ct201345_h2o_glm.tif")
ct201345_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/ct201345_rf.tif")
ct201345_h2o_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/ct201345_h2o_rf.tif")
auc_ct_201345 <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_201345.csv")
auc_ct_201345_h2o <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_201345_h2o.csv")

#ensemble no water
pred_stack_ct201345 <- stack(x = c(ct201345_glm, ct201345_rf))
weights_ct201345 <- auc_ct_201345$AUC / sum(auc_ct_201345$AUC)
ensemble_pred_ct201345 <- weighted.mean(pred_stack_ct201345, w = weights_ct201345)
plot(ensemble_pred_ct201345)
writeRaster(ensemble_pred_ct201345, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_ct201345.tif")

#using test data now to get AUC 
test_data_ct <- read.csv(here("Natalie/data_cleaned/test_train/test_data_ct.csv"))
test_coords_ct <- test_data_ct[, c("Longitude", "Latitude")]
test_presence_ct <- as.numeric(test_data_ct$ct)
ensemble_test_pred_ct201345 <- extract(ensemble_pred_ct201345, test_coords_ct, pos_label = 1)
ensemble_auc_df_ct201345 <- data.frame(test_data_ct$X, test_presence_ct, ensemble_test_pred_ct201345)
auc_ensemble_ct201345<- PresenceAbsence ::auc(ensemble_auc_df_ct201345, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_ct201345, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_ct201345.csv")

#h2o
pred_stack_ct201345_h2o <- stack(x = c(ct201345_h2o_glm, ct201345_h2o_rf))
weights_ct201345_h2o <- auc_ct_201345_h2o$AUC / sum(auc_ct_201345_h2o$AUC)

ensemble_pred_ct201345_h2o <- weighted.mean(pred_stack_ct201345_h2o, w = weights_ct201345_h2o)
plot(ensemble_pred_ct201345_h2o)
writeRaster(ensemble_pred_ct201345_h2o, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_ct201345_h2o.tif")

#using test data now to get AUC
test_data_ct <- read.csv(here("Natalie/data_cleaned/test_train/test_data_ct.csv"))
test_coords_ct <- test_data_ct[, c("Longitude", "Latitude")]
test_presence_ct <- as.numeric(test_data_ct$ct)
ensemble_test_pred_ct201345_h2o <- extract(ensemble_pred_ct201345_h2o, test_coords_ct, pos_label = 1)
ensemble_auc_df_ct201345_h2o <- data.frame(test_data_ct$X, test_presence_ct, ensemble_test_pred_ct201345_h2o)
auc_ensemble_ct201345_h2o<- PresenceAbsence ::auc(ensemble_auc_df_ct201345, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_ct201345_h2o, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_ct201345_h2o.csv")


#YW201919
ct201919_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/ct201919_glm.tif")
ct201919_h2o_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/ct201919_h2o_glm.tif")
ct201919_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/ct201919_rf.tif")
ct201919_h2o_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/ct201919_h2o_rf.tif")
auc_ct_201919 <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_201919.csv")
auc_ct_201919_h2o <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_201919_h2o.csv")

#ensemble no water
pred_stack_ct201919 <- stack(x = c(ct201919_glm, ct201919_rf))
weights_ct201919 <- auc_ct_201919$AUC / sum(auc_ct_201919$AUC)
ensemble_pred_ct201919 <- weighted.mean(pred_stack_ct201919, w = weights_ct201919)
plot(ensemble_pred_ct201919)
writeRaster(ensemble_pred_ct201919, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_ct201919.tif")

#using test data now to get AUC 
test_data_ct <- read.csv(here("Natalie/data_cleaned/test_train/test_data_ct.csv"))
test_coords_ct <- test_data_ct[, c("Longitude", "Latitude")]
test_presence_ct <- as.numeric(test_data_ct$ct)
ensemble_test_pred_ct201919 <- extract(ensemble_pred_ct201919, test_coords_ct, pos_label = 1)
ensemble_auc_df_ct201919 <- data.frame(test_data_ct$X, test_presence_ct, ensemble_test_pred_ct201919)
auc_ensemble_ct201919<- PresenceAbsence ::auc(ensemble_auc_df_ct201919, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_ct201919, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_ct201919.csv")

#h2o
pred_stack_ct201919_h2o <- stack(x = c(ct201919_h2o_glm, ct201919_h2o_rf))
weights_ct201919_h2o <- auc_ct_201919_h2o$AUC / sum(auc_ct_201919_h2o$AUC)

ensemble_pred_ct201919_h2o <- weighted.mean(pred_stack_ct201919_h2o, w = weights_ct201919_h2o)
plot(ensemble_pred_ct201919_h2o)
writeRaster(ensemble_pred_ct201919_h2o, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_ct201919_h2o.tif")

#using test data now to get AUC
test_data_ct <- read.csv(here("Natalie/data_cleaned/test_train/test_data_ct.csv"))
test_coords_ct <- test_data_ct[, c("Longitude", "Latitude")]
test_presence_ct <- as.numeric(test_data_ct$ct)
ensemble_test_pred_ct201919_h2o <- extract(ensemble_pred_ct201919_h2o, test_coords_ct, pos_label = 1)
ensemble_auc_df_ct201919_h2o <- data.frame(test_data_ct$X, test_presence_ct, ensemble_test_pred_ct201919_h2o)
auc_ensemble_ct201919_h2o<- PresenceAbsence ::auc(ensemble_auc_df_ct201919, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_ct201919_h2o, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_ct201919_h2o.csv")



#**YW201932*
ct201932_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/ct201932_glm.tif")
ct201932_h2o_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/ct201932_h2o_glm.tif")
ct201932_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/ct201932_rf.tif")
ct201932_h2o_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/ct201932_h2o_rf.tif")
auc_ct_201932 <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_201932.csv")
auc_ct_201932_h2o <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_201932_h2o.csv")

#ensemble no water
pred_stack_ct201932 <- stack(x = c(ct201932_glm, ct201932_rf))
weights_ct201932 <- auc_ct_201932$AUC / sum(auc_ct_201932$AUC)
ensemble_pred_ct201932 <- weighted.mean(pred_stack_ct201932, w = weights_ct201932)
plot(ensemble_pred_ct201932)
writeRaster(ensemble_pred_ct201932, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_ct201932.tif")

#using test data now to get AUC 
test_data_ct <- read.csv(here("Natalie/data_cleaned/test_train/test_data_ct.csv"))
test_coords_ct <- test_data_ct[, c("Longitude", "Latitude")]
test_presence_ct <- as.numeric(test_data_ct$ct)
ensemble_test_pred_ct201932 <- extract(ensemble_pred_ct201932, test_coords_ct, pos_label = 1)
ensemble_auc_df_ct201932 <- data.frame(test_data_ct$X, test_presence_ct, ensemble_test_pred_ct201932)
auc_ensemble_ct201932<- PresenceAbsence ::auc(ensemble_auc_df_ct201932, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_ct201932, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_ct201932.csv")

#h2o
pred_stack_ct201932_h2o <- stack(x = c(ct201932_h2o_glm, ct201932_h2o_rf))
weights_ct201932_h2o <- auc_ct_201932_h2o$AUC / sum(auc_ct_201932_h2o$AUC)

ensemble_pred_ct201932_h2o <- weighted.mean(pred_stack_ct201932_h2o, w = weights_ct201932_h2o)
plot(ensemble_pred_ct201932_h2o)
writeRaster(ensemble_pred_ct201932_h2o, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_ct201932_h2o.tif")

#using test data now to get AUC
test_data_ct <- read.csv(here("Natalie/data_cleaned/test_train/test_data_ct.csv"))
test_coords_ct <- test_data_ct[, c("Longitude", "Latitude")]
test_presence_ct <- as.numeric(test_data_ct$ct)
ensemble_test_pred_ct201932_h2o <- extract(ensemble_pred_ct201932_h2o, test_coords_ct, pos_label = 1)
ensemble_auc_df_ct201932_h2o <- data.frame(test_data_ct$X, test_presence_ct, ensemble_test_pred_ct201932_h2o)
auc_ensemble_ct201932_h2o<- PresenceAbsence ::auc(ensemble_auc_df_ct201932, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_ct201932_h2o, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_ct201932_h2o.csv")



#**YW201945**
ct201945_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/ct201945_glm.tif")
ct201945_h2o_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/ct201945_h2o_glm.tif")
ct201945_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/ct201945_rf.tif")
ct201945_h2o_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/ct201945_h2o_rf.tif")
auc_ct_201945 <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_201945.csv")
auc_ct_201945_h2o <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_201945_h2o.csv")

#ensemble no water
pred_stack_ct201945 <- stack(x = c(ct201945_glm, ct201945_rf))
weights_ct201945 <- auc_ct_201945$AUC / sum(auc_ct_201945$AUC)
ensemble_pred_ct201945 <- weighted.mean(pred_stack_ct201945, w = weights_ct201945)
plot(ensemble_pred_ct201945)
writeRaster(ensemble_pred_ct201945, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_ct201945.tif")

#using test data now to get AUC 
test_data_ct <- read.csv(here("Natalie/data_cleaned/test_train/test_data_ct.csv"))
test_coords_ct <- test_data_ct[, c("Longitude", "Latitude")]
test_presence_ct <- as.numeric(test_data_ct$ct)
ensemble_test_pred_ct201945 <- extract(ensemble_pred_ct201945, test_coords_ct, pos_label = 1)
ensemble_auc_df_ct201945 <- data.frame(test_data_ct$X, test_presence_ct, ensemble_test_pred_ct201945)
auc_ensemble_ct201945<- PresenceAbsence ::auc(ensemble_auc_df_ct201945, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_ct201945, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_ct201945.csv")

#h2o
pred_stack_ct201945_h2o <- stack(x = c(ct201945_h2o_glm, ct201945_h2o_rf))
weights_ct201945_h2o <- auc_ct_201945_h2o$AUC / sum(auc_ct_201945_h2o$AUC)

ensemble_pred_ct201945_h2o <- weighted.mean(pred_stack_ct201945_h2o, w = weights_ct201945_h2o)
plot(ensemble_pred_ct201945_h2o)
writeRaster(ensemble_pred_ct201945_h2o, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_ct201945_h2o.tif")

#using test data now to get AUC
test_data_ct <- read.csv(here("Natalie/data_cleaned/test_train/test_data_ct.csv"))
test_coords_ct <- test_data_ct[, c("Longitude", "Latitude")]
test_presence_ct <- as.numeric(test_data_ct$ct)
ensemble_test_pred_ct201945_h2o <- extract(ensemble_pred_ct201945_h2o, test_coords_ct, pos_label = 1)
ensemble_auc_df_ct201945_h2o <- data.frame(test_data_ct$X, test_presence_ct, ensemble_test_pred_ct201945_h2o)
auc_ensemble_ct201945_h2o<- PresenceAbsence ::auc(ensemble_auc_df_ct201945, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_ct201945_h2o, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_ct201945_h2o.csv")



#**YW202119*
ct202119_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/ct202119_glm.tif")
ct202119_h2o_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/ct202119_h2o_glm.tif")
ct202119_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/ct202119_rf.tif")
ct202119_h2o_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/ct202119_h2o_rf.tif")
auc_ct_202119 <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_202119.csv")
auc_ct_202119_h2o <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_202119_h2o.csv")

#ensemble no water
pred_stack_ct202119 <- stack(x = c(ct202119_glm, ct202119_rf))
weights_ct202119 <- auc_ct_202119$AUC / sum(auc_ct_202119$AUC)
ensemble_pred_ct202119 <- weighted.mean(pred_stack_ct202119, w = weights_ct202119)
plot(ensemble_pred_ct202119)
writeRaster(ensemble_pred_ct202119, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_ct202119.tif")

#using test data now to get AUC 
test_data_ct <- read.csv(here("Natalie/data_cleaned/test_train/test_data_ct.csv"))
test_coords_ct <- test_data_ct[, c("Longitude", "Latitude")]
test_presence_ct <- as.numeric(test_data_ct$ct)
ensemble_test_pred_ct202119 <- extract(ensemble_pred_ct202119, test_coords_ct, pos_label = 1)
ensemble_auc_df_ct202119 <- data.frame(test_data_ct$X, test_presence_ct, ensemble_test_pred_ct202119)
auc_ensemble_ct202119<- PresenceAbsence ::auc(ensemble_auc_df_ct202119, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_ct202119, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_ct202119.csv")

#h2o
pred_stack_ct202119_h2o <- stack(x = c(ct202119_h2o_glm, ct202119_h2o_rf))
weights_ct202119_h2o <- auc_ct_202119_h2o$AUC / sum(auc_ct_202119_h2o$AUC)

ensemble_pred_ct202119_h2o <- weighted.mean(pred_stack_ct202119_h2o, w = weights_ct202119_h2o)
plot(ensemble_pred_ct202119_h2o)
writeRaster(ensemble_pred_ct202119_h2o, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_ct202119_h2o.tif")

#using test data now to get AUC
test_data_ct <- read.csv(here("Natalie/data_cleaned/test_train/test_data_ct.csv"))
test_coords_ct <- test_data_ct[, c("Longitude", "Latitude")]
test_presence_ct <- as.numeric(test_data_ct$ct)
ensemble_test_pred_ct202119_h2o <- extract(ensemble_pred_ct202119_h2o, test_coords_ct, pos_label = 1)
ensemble_auc_df_ct202119_h2o <- data.frame(test_data_ct$X, test_presence_ct, ensemble_test_pred_ct202119_h2o)
auc_ensemble_ct202119_h2o<- PresenceAbsence ::auc(ensemble_auc_df_ct202119, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_ct202119_h2o, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_ct202119_h2o.csv")


#**YW202132*
ct202132_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/ct202132_glm.tif")
ct202132_h2o_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/ct202132_h2o_glm.tif")
ct202132_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/ct202132_rf.tif")
ct202132_h2o_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/ct202132_h2o_rf.tif")
auc_ct_202132 <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_202132.csv")
auc_ct_202132_h2o <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_202132_h2o.csv")

#ensemble no water
pred_stack_ct202132 <- stack(x = c(ct202132_glm, ct202132_rf))
weights_ct202132 <- auc_ct_202132$AUC / sum(auc_ct_202132$AUC)
ensemble_pred_ct202132 <- weighted.mean(pred_stack_ct202132, w = weights_ct202132)
plot(ensemble_pred_ct202132)
writeRaster(ensemble_pred_ct202132, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_ct202132.tif")

#using test data now to get AUC 
test_data_ct <- read.csv(here("Natalie/data_cleaned/test_train/test_data_ct.csv"))
test_coords_ct <- test_data_ct[, c("Longitude", "Latitude")]
test_presence_ct <- as.numeric(test_data_ct$ct)
ensemble_test_pred_ct202132 <- extract(ensemble_pred_ct202132, test_coords_ct, pos_label = 1)
ensemble_auc_df_ct202132 <- data.frame(test_data_ct$X, test_presence_ct, ensemble_test_pred_ct202132)
auc_ensemble_ct202132<- PresenceAbsence ::auc(ensemble_auc_df_ct202132, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_ct202132, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_ct202132.csv")

#h2o
pred_stack_ct202132_h2o <- stack(x = c(ct202132_h2o_glm, ct202132_h2o_rf))
weights_ct202132_h2o <- auc_ct_202132_h2o$AUC / sum(auc_ct_202132_h2o$AUC)

ensemble_pred_ct202132_h2o <- weighted.mean(pred_stack_ct202132_h2o, w = weights_ct202132_h2o)
plot(ensemble_pred_ct202132_h2o)
writeRaster(ensemble_pred_ct202132_h2o, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_ct202132_h2o.tif")

#using test data now to get AUC
test_data_ct <- read.csv(here("Natalie/data_cleaned/test_train/test_data_ct.csv"))
test_coords_ct <- test_data_ct[, c("Longitude", "Latitude")]
test_presence_ct <- as.numeric(test_data_ct$ct)
ensemble_test_pred_ct202132_h2o <- extract(ensemble_pred_ct202132_h2o, test_coords_ct, pos_label = 1)
ensemble_auc_df_ct202132_h2o <- data.frame(test_data_ct$X, test_presence_ct, ensemble_test_pred_ct202132_h2o)
auc_ensemble_ct202132_h2o<- PresenceAbsence ::auc(ensemble_auc_df_ct202132, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_ct202132_h2o, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_ct202132_h2o.csv")


#**YW202145*
ct202145_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/ct202145_glm.tif")
ct202145_h2o_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/ct202145_h2o_glm.tif")
ct202145_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/ct202145_rf.tif")
ct202145_h2o_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/ct202145_h2o_rf.tif")
auc_ct_202145 <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_202145.csv")
auc_ct_202145_h2o <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_ct_202145_h2o.csv")

#ensemble no water
pred_stack_ct202145 <- stack(x = c(ct202145_glm, ct202145_rf))
weights_ct202145 <- auc_ct_202145$AUC / sum(auc_ct_202145$AUC)
ensemble_pred_ct202145 <- weighted.mean(pred_stack_ct202145, w = weights_ct202145)
plot(ensemble_pred_ct202145)
writeRaster(ensemble_pred_ct202145, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_ct202145.tif")

#using test data now to get AUC 
test_data_ct <- read.csv(here("Natalie/data_cleaned/test_train/test_data_ct.csv"))
test_coords_ct <- test_data_ct[, c("Longitude", "Latitude")]
test_presence_ct <- as.numeric(test_data_ct$ct)
ensemble_test_pred_ct202145 <- extract(ensemble_pred_ct202145, test_coords_ct, pos_label = 1)
ensemble_auc_df_ct202145 <- data.frame(test_data_ct$X, test_presence_ct, ensemble_test_pred_ct202145)
auc_ensemble_ct202145<- PresenceAbsence ::auc(ensemble_auc_df_ct202145, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_ct202145, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_ct202145.csv")

#h2o
pred_stack_ct202145_h2o <- stack(x = c(ct202145_h2o_glm, ct202145_h2o_rf))
weights_ct202145_h2o <- auc_ct_202145_h2o$AUC / sum(auc_ct_202145_h2o$AUC)

ensemble_pred_ct202145_h2o <- weighted.mean(pred_stack_ct202145_h2o, w = weights_ct202145_h2o)
plot(ensemble_pred_ct202145_h2o)
writeRaster(ensemble_pred_ct202145_h2o, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_ct202145_h2o.tif")

#using test data now to get AUC
test_data_ct <- read.csv(here("Natalie/data_cleaned/test_train/test_data_ct.csv"))
test_coords_ct <- test_data_ct[, c("Longitude", "Latitude")]
test_presence_ct <- as.numeric(test_data_ct$ct)
ensemble_test_pred_ct202145_h2o <- extract(ensemble_pred_ct202145_h2o, test_coords_ct, pos_label = 1)
ensemble_auc_df_ct202145_h2o <- data.frame(test_data_ct$X, test_presence_ct, ensemble_test_pred_ct202145_h2o)
auc_ensemble_ct202145_h2o<- PresenceAbsence ::auc(ensemble_auc_df_ct202145, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_ct202145_h2o, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_ct202145_h2o.csv")


```


Ensemble AA
```{r}

#**YW201319*
aa201319_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/aa201319_glm.tif")
aa201319_h2o_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/aa201319_h2o_glm.tif")
aa201319_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/aa201319_rf.tif")
aa201319_h2o_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/aa201319_h2o_rf.tif")
auc_aa_201319 <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_201319.csv")
auc_aa_201319_h2o <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_201319_h2o.csv")

#ensemble no water
pred_stack_aa201319 <- stack(x = c(aa201319_glm, aa201319_rf))
weights_aa201319 <- auc_aa_201319$AUC / sum(auc_aa_201319$AUC)
ensemble_pred_aa201319 <- weighted.mean(pred_stack_aa201319, w = weights_aa201319)
plot(ensemble_pred_aa201319)
writeRaster(ensemble_pred_aa201319, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_aa201319.tif")

#using test data now to get AUC 
test_data_aa <- read.csv(here("Natalie/data_cleaned/test_train/test_data_aa.csv"))
test_coords_aa <- test_data_aa[, c("Longitude", "Latitude")]
test_presence_aa <- as.numeric(test_data_aa$aa)
ensemble_test_pred_aa201319 <- extract(ensemble_pred_aa201319, test_coords_aa, pos_label = 1)
ensemble_auc_df_aa201319 <- data.frame(test_data_aa$X, test_presence_aa, ensemble_test_pred_aa201319)
auc_ensemble_aa201319<- PresenceAbsence ::auc(ensemble_auc_df_aa201319, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_aa201319, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_aa201319.csv")

#h2o
pred_stack_aa201319_h2o <- stack(x = c(aa201319_h2o_glm, aa201319_h2o_rf))
weights_aa201319_h2o <- auc_aa_201319_h2o$AUC / sum(auc_aa_201319_h2o$AUC)

ensemble_pred_aa201319_h2o <- weighted.mean(pred_stack_aa201319_h2o, w = weights_aa201319_h2o)
plot(ensemble_pred_aa201319_h2o)
writeRaster(ensemble_pred_aa201319_h2o, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_aa201319_h2o.tif")

#using test data now to get AUC
test_data_aa <- read.csv(here("Natalie/data_cleaned/test_train/test_data_aa.csv"))
test_coords_aa <- test_data_aa[, c("Longitude", "Latitude")]
test_presence_aa <- as.numeric(test_data_aa$aa)
ensemble_test_pred_aa201319_h2o <- extract(ensemble_pred_aa201319_h2o, test_coords_aa, pos_label = 1)
ensemble_auc_df_aa201319_h2o <- data.frame(test_data_aa$X, test_presence_aa, ensemble_test_pred_aa201319_h2o)
auc_ensemble_aa201319_h2o<- PresenceAbsence ::auc(ensemble_auc_df_aa201319, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_aa201319_h2o, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_aa201319_h2o.csv")

#**YW201332*
aa201332_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/aa201332_glm.tif")
aa201332_h2o_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/aa201332_h2o_glm.tif")
aa201332_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/aa201332_rf.tif")
aa201332_h2o_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/aa201332_h2o_rf.tif")
auc_aa_201332 <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_201332.csv")
auc_aa_201332_h2o <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_201332_h2o.csv")

#ensemble no water
pred_stack_aa201332 <- stack(x = c(aa201332_glm, aa201332_rf))
weights_aa201332 <- auc_aa_201332$AUC / sum(auc_aa_201332$AUC)
ensemble_pred_aa201332 <- weighted.mean(pred_stack_aa201332, w = weights_aa201332)
plot(ensemble_pred_aa201332)
writeRaster(ensemble_pred_aa201332, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_aa201332.tif")

#using test data now to get AUC 
test_data_aa <- read.csv(here("Natalie/data_cleaned/test_train/test_data_aa.csv"))
test_coords_aa <- test_data_aa[, c("Longitude", "Latitude")]
test_presence_aa <- as.numeric(test_data_aa$aa)
ensemble_test_pred_aa201332 <- extract(ensemble_pred_aa201332, test_coords_aa, pos_label = 1)
ensemble_auc_df_aa201332 <- data.frame(test_data_aa$X, test_presence_aa, ensemble_test_pred_aa201332)
auc_ensemble_aa201332<- PresenceAbsence ::auc(ensemble_auc_df_aa201332, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_aa201332, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_aa201332.csv")

#h2o
pred_stack_aa201332_h2o <- stack(x = c(aa201332_h2o_glm, aa201332_h2o_rf))
weights_aa201332_h2o <- auc_aa_201332_h2o$AUC / sum(auc_aa_201332_h2o$AUC)

ensemble_pred_aa201332_h2o <- weighted.mean(pred_stack_aa201332_h2o, w = weights_aa201332_h2o)
plot(ensemble_pred_aa201332_h2o)
writeRaster(ensemble_pred_aa201332_h2o, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_aa201332_h2o.tif")

#using test data now to get AUC
test_data_aa <- read.csv(here("Natalie/data_cleaned/test_train/test_data_aa.csv"))
test_coords_aa <- test_data_aa[, c("Longitude", "Latitude")]
test_presence_aa <- as.numeric(test_data_aa$aa)
ensemble_test_pred_aa201332_h2o <- extract(ensemble_pred_aa201332_h2o, test_coords_aa, pos_label = 1)
ensemble_auc_df_aa201332_h2o <- data.frame(test_data_aa$X, test_presence_aa, ensemble_test_pred_aa201332_h2o)
auc_ensemble_aa201332_h2o<- PresenceAbsence ::auc(ensemble_auc_df_aa201332, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_aa201332_h2o, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_aa201332_h2o.csv")


#**YW201345*
aa201345_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/aa201345_glm.tif")
aa201345_h2o_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/aa201345_h2o_glm.tif")
aa201345_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/aa201345_rf.tif")
aa201345_h2o_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/aa201345_h2o_rf.tif")
auc_aa_201345 <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_201345.csv")
auc_aa_201345_h2o <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_201345_h2o.csv")

#ensemble no water
pred_stack_aa201345 <- stack(x = c(aa201345_glm, aa201345_rf))
weights_aa201345 <- auc_aa_201345$AUC / sum(auc_aa_201345$AUC)
ensemble_pred_aa201345 <- weighted.mean(pred_stack_aa201345, w = weights_aa201345)
plot(ensemble_pred_aa201345)
writeRaster(ensemble_pred_aa201345, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_aa201345.tif")

#using test data now to get AUC 
test_data_aa <- read.csv(here("Natalie/data_cleaned/test_train/test_data_aa.csv"))
test_coords_aa <- test_data_aa[, c("Longitude", "Latitude")]
test_presence_aa <- as.numeric(test_data_aa$aa)
ensemble_test_pred_aa201345 <- extract(ensemble_pred_aa201345, test_coords_aa, pos_label = 1)
ensemble_auc_df_aa201345 <- data.frame(test_data_aa$X, test_presence_aa, ensemble_test_pred_aa201345)
auc_ensemble_aa201345<- PresenceAbsence ::auc(ensemble_auc_df_aa201345, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_aa201345, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_aa201345.csv")

#h2o
pred_stack_aa201345_h2o <- stack(x = c(aa201345_h2o_glm, aa201345_h2o_rf))
weights_aa201345_h2o <- auc_aa_201345_h2o$AUC / sum(auc_aa_201345_h2o$AUC)

ensemble_pred_aa201345_h2o <- weighted.mean(pred_stack_aa201345_h2o, w = weights_aa201345_h2o)
plot(ensemble_pred_aa201345_h2o)
writeRaster(ensemble_pred_aa201345_h2o, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_aa201345_h2o.tif")

#using test data now to get AUC
test_data_aa <- read.csv(here("Natalie/data_cleaned/test_train/test_data_aa.csv"))
test_coords_aa <- test_data_aa[, c("Longitude", "Latitude")]
test_presence_aa <- as.numeric(test_data_aa$aa)
ensemble_test_pred_aa201345_h2o <- extract(ensemble_pred_aa201345_h2o, test_coords_aa, pos_label = 1)
ensemble_auc_df_aa201345_h2o <- data.frame(test_data_aa$X, test_presence_aa, ensemble_test_pred_aa201345_h2o)
auc_ensemble_aa201345_h2o<- PresenceAbsence ::auc(ensemble_auc_df_aa201345, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_aa201345_h2o, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_aa201345_h2o.csv")


#YW201919
aa201919_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/aa201919_glm.tif")
aa201919_h2o_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/aa201919_h2o_glm.tif")
aa201919_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/aa201919_rf.tif")
aa201919_h2o_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/aa201919_h2o_rf.tif")
auc_aa_201919 <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_201919.csv")
auc_aa_201919_h2o <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_201919_h2o.csv")

#ensemble no water
pred_stack_aa201919 <- stack(x = c(aa201919_glm, aa201919_rf))
weights_aa201919 <- auc_aa_201919$AUC / sum(auc_aa_201919$AUC)
ensemble_pred_aa201919 <- weighted.mean(pred_stack_aa201919, w = weights_aa201919)
plot(ensemble_pred_aa201919)
writeRaster(ensemble_pred_aa201919, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_aa201919.tif")

#using test data now to get AUC 
test_data_aa <- read.csv(here("Natalie/data_cleaned/test_train/test_data_aa.csv"))
test_coords_aa <- test_data_aa[, c("Longitude", "Latitude")]
test_presence_aa <- as.numeric(test_data_aa$aa)
ensemble_test_pred_aa201919 <- extract(ensemble_pred_aa201919, test_coords_aa, pos_label = 1)
ensemble_auc_df_aa201919 <- data.frame(test_data_aa$X, test_presence_aa, ensemble_test_pred_aa201919)
auc_ensemble_aa201919<- PresenceAbsence ::auc(ensemble_auc_df_aa201919, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_aa201919, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_aa201919.csv")

#h2o
pred_stack_aa201919_h2o <- stack(x = c(aa201919_h2o_glm, aa201919_h2o_rf))
weights_aa201919_h2o <- auc_aa_201919_h2o$AUC / sum(auc_aa_201919_h2o$AUC)

ensemble_pred_aa201919_h2o <- weighted.mean(pred_stack_aa201919_h2o, w = weights_aa201919_h2o)
plot(ensemble_pred_aa201919_h2o)
writeRaster(ensemble_pred_aa201919_h2o, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_aa201919_h2o.tif")

#using test data now to get AUC
test_data_aa <- read.csv(here("Natalie/data_cleaned/test_train/test_data_aa.csv"))
test_coords_aa <- test_data_aa[, c("Longitude", "Latitude")]
test_presence_aa <- as.numeric(test_data_aa$aa)
ensemble_test_pred_aa201919_h2o <- extract(ensemble_pred_aa201919_h2o, test_coords_aa, pos_label = 1)
ensemble_auc_df_aa201919_h2o <- data.frame(test_data_aa$X, test_presence_aa, ensemble_test_pred_aa201919_h2o)
auc_ensemble_aa201919_h2o<- PresenceAbsence ::auc(ensemble_auc_df_aa201919, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_aa201919_h2o, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_aa201919_h2o.csv")



#**YW201932*
aa201932_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/aa201932_glm.tif")
aa201932_h2o_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/aa201932_h2o_glm.tif")
aa201932_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/aa201932_rf.tif")
aa201932_h2o_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/aa201932_h2o_rf.tif")
auc_aa_201932 <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_201932.csv")
auc_aa_201932_h2o <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_201932_h2o.csv")

#ensemble no water
pred_stack_aa201932 <- stack(x = c(aa201932_glm, aa201932_rf))
weights_aa201932 <- auc_aa_201932$AUC / sum(auc_aa_201932$AUC)
ensemble_pred_aa201932 <- weighted.mean(pred_stack_aa201932, w = weights_aa201932)
plot(ensemble_pred_aa201932)
writeRaster(ensemble_pred_aa201932, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_aa201932.tif")

#using test data now to get AUC 
test_data_aa <- read.csv(here("Natalie/data_cleaned/test_train/test_data_aa.csv"))
test_coords_aa <- test_data_aa[, c("Longitude", "Latitude")]
test_presence_aa <- as.numeric(test_data_aa$aa)
ensemble_test_pred_aa201932 <- extract(ensemble_pred_aa201932, test_coords_aa, pos_label = 1)
ensemble_auc_df_aa201932 <- data.frame(test_data_aa$X, test_presence_aa, ensemble_test_pred_aa201932)
auc_ensemble_aa201932<- PresenceAbsence ::auc(ensemble_auc_df_aa201932, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_aa201932, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_aa201932.csv")

#h2o
pred_stack_aa201932_h2o <- stack(x = c(aa201932_h2o_glm, aa201932_h2o_rf))
weights_aa201932_h2o <- auc_aa_201932_h2o$AUC / sum(auc_aa_201932_h2o$AUC)

ensemble_pred_aa201932_h2o <- weighted.mean(pred_stack_aa201932_h2o, w = weights_aa201932_h2o)
plot(ensemble_pred_aa201932_h2o)
writeRaster(ensemble_pred_aa201932_h2o, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_aa201932_h2o.tif")

#using test data now to get AUC
test_data_aa <- read.csv(here("Natalie/data_cleaned/test_train/test_data_aa.csv"))
test_coords_aa <- test_data_aa[, c("Longitude", "Latitude")]
test_presence_aa <- as.numeric(test_data_aa$aa)
ensemble_test_pred_aa201932_h2o <- extract(ensemble_pred_aa201932_h2o, test_coords_aa, pos_label = 1)
ensemble_auc_df_aa201932_h2o <- data.frame(test_data_aa$X, test_presence_aa, ensemble_test_pred_aa201932_h2o)
auc_ensemble_aa201932_h2o<- PresenceAbsence ::auc(ensemble_auc_df_aa201932, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_aa201932_h2o, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_aa201932_h2o.csv")



#**YW201945**
aa201945_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/aa201945_glm.tif")
aa201945_h2o_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/aa201945_h2o_glm.tif")
aa201945_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/aa201945_rf.tif")
aa201945_h2o_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/aa201945_h2o_rf.tif")
auc_aa_201945 <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_201945.csv")
auc_aa_201945_h2o <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_201945_h2o.csv")

#ensemble no water
pred_stack_aa201945 <- stack(x = c(aa201945_glm, aa201945_rf))
weights_aa201945 <- auc_aa_201945$AUC / sum(auc_aa_201945$AUC)
ensemble_pred_aa201945 <- weighted.mean(pred_stack_aa201945, w = weights_aa201945)
plot(ensemble_pred_aa201945)
writeRaster(ensemble_pred_aa201945, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_aa201945.tif")

#using test data now to get AUC 
test_data_aa <- read.csv(here("Natalie/data_cleaned/test_train/test_data_aa.csv"))
test_coords_aa <- test_data_aa[, c("Longitude", "Latitude")]
test_presence_aa <- as.numeric(test_data_aa$aa)
ensemble_test_pred_aa201945 <- extract(ensemble_pred_aa201945, test_coords_aa, pos_label = 1)
ensemble_auc_df_aa201945 <- data.frame(test_data_aa$X, test_presence_aa, ensemble_test_pred_aa201945)
auc_ensemble_aa201945<- PresenceAbsence ::auc(ensemble_auc_df_aa201945, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_aa201945, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_aa201945.csv")

#h2o
pred_stack_aa201945_h2o <- stack(x = c(aa201945_h2o_glm, aa201945_h2o_rf))
weights_aa201945_h2o <- auc_aa_201945_h2o$AUC / sum(auc_aa_201945_h2o$AUC)

ensemble_pred_aa201945_h2o <- weighted.mean(pred_stack_aa201945_h2o, w = weights_aa201945_h2o)
plot(ensemble_pred_aa201945_h2o)
writeRaster(ensemble_pred_aa201945_h2o, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_aa201945_h2o.tif")

#using test data now to get AUC
test_data_aa <- read.csv(here("Natalie/data_cleaned/test_train/test_data_aa.csv"))
test_coords_aa <- test_data_aa[, c("Longitude", "Latitude")]
test_presence_aa <- as.numeric(test_data_aa$aa)
ensemble_test_pred_aa201945_h2o <- extract(ensemble_pred_aa201945_h2o, test_coords_aa, pos_label = 1)
ensemble_auc_df_aa201945_h2o <- data.frame(test_data_aa$X, test_presence_aa, ensemble_test_pred_aa201945_h2o)
auc_ensemble_aa201945_h2o<- PresenceAbsence ::auc(ensemble_auc_df_aa201945, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_aa201945_h2o, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_aa201945_h2o.csv")



#**YW202119*
aa202119_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/aa202119_glm.tif")
aa202119_h2o_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/aa202119_h2o_glm.tif")
aa202119_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/aa202119_rf.tif")
aa202119_h2o_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/aa202119_h2o_rf.tif")
auc_aa_202119 <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_202119.csv")
auc_aa_202119_h2o <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_202119_h2o.csv")

#ensemble no water
pred_stack_aa202119 <- stack(x = c(aa202119_glm, aa202119_rf))
weights_aa202119 <- auc_aa_202119$AUC / sum(auc_aa_202119$AUC)
ensemble_pred_aa202119 <- weighted.mean(pred_stack_aa202119, w = weights_aa202119)
plot(ensemble_pred_aa202119)
writeRaster(ensemble_pred_aa202119, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_aa202119.tif")

#using test data now to get AUC 
test_data_aa <- read.csv(here("Natalie/data_cleaned/test_train/test_data_aa.csv"))
test_coords_aa <- test_data_aa[, c("Longitude", "Latitude")]
test_presence_aa <- as.numeric(test_data_aa$aa)
ensemble_test_pred_aa202119 <- extract(ensemble_pred_aa202119, test_coords_aa, pos_label = 1)
ensemble_auc_df_aa202119 <- data.frame(test_data_aa$X, test_presence_aa, ensemble_test_pred_aa202119)
auc_ensemble_aa202119<- PresenceAbsence ::auc(ensemble_auc_df_aa202119, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_aa202119, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_aa202119.csv")

#h2o
pred_stack_aa202119_h2o <- stack(x = c(aa202119_h2o_glm, aa202119_h2o_rf))
weights_aa202119_h2o <- auc_aa_202119_h2o$AUC / sum(auc_aa_202119_h2o$AUC)

ensemble_pred_aa202119_h2o <- weighted.mean(pred_stack_aa202119_h2o, w = weights_aa202119_h2o)
plot(ensemble_pred_aa202119_h2o)
writeRaster(ensemble_pred_aa202119_h2o, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_aa202119_h2o.tif")

#using test data now to get AUC
test_data_aa <- read.csv(here("Natalie/data_cleaned/test_train/test_data_aa.csv"))
test_coords_aa <- test_data_aa[, c("Longitude", "Latitude")]
test_presence_aa <- as.numeric(test_data_aa$aa)
ensemble_test_pred_aa202119_h2o <- extract(ensemble_pred_aa202119_h2o, test_coords_aa, pos_label = 1)
ensemble_auc_df_aa202119_h2o <- data.frame(test_data_aa$X, test_presence_aa, ensemble_test_pred_aa202119_h2o)
auc_ensemble_aa202119_h2o<- PresenceAbsence ::auc(ensemble_auc_df_aa202119, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_aa202119_h2o, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_aa202119_h2o.csv")


#**YW202132*
aa202132_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/aa202132_glm.tif")
aa202132_h2o_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/aa202132_h2o_glm.tif")
aa202132_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/aa202132_rf.tif")
aa202132_h2o_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/aa202132_h2o_rf.tif")
auc_aa_202132 <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_202132.csv")
auc_aa_202132_h2o <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_202132_h2o.csv")

#ensemble no water
pred_stack_aa202132 <- stack(x = c(aa202132_glm, aa202132_rf))
weights_aa202132 <- auc_aa_202132$AUC / sum(auc_aa_202132$AUC)
ensemble_pred_aa202132 <- weighted.mean(pred_stack_aa202132, w = weights_aa202132)
plot(ensemble_pred_aa202132)
writeRaster(ensemble_pred_aa202132, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_aa202132.tif")

#using test data now to get AUC 
test_data_aa <- read.csv(here("Natalie/data_cleaned/test_train/test_data_aa.csv"))
test_coords_aa <- test_data_aa[, c("Longitude", "Latitude")]
test_presence_aa <- as.numeric(test_data_aa$aa)
ensemble_test_pred_aa202132 <- extract(ensemble_pred_aa202132, test_coords_aa, pos_label = 1)
ensemble_auc_df_aa202132 <- data.frame(test_data_aa$X, test_presence_aa, ensemble_test_pred_aa202132)
auc_ensemble_aa202132<- PresenceAbsence ::auc(ensemble_auc_df_aa202132, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_aa202132, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_aa202132.csv")

#h2o
pred_stack_aa202132_h2o <- stack(x = c(aa202132_h2o_glm, aa202132_h2o_rf))
weights_aa202132_h2o <- auc_aa_202132_h2o$AUC / sum(auc_aa_202132_h2o$AUC)

ensemble_pred_aa202132_h2o <- weighted.mean(pred_stack_aa202132_h2o, w = weights_aa202132_h2o)
plot(ensemble_pred_aa202132_h2o)
writeRaster(ensemble_pred_aa202132_h2o, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_aa202132_h2o.tif")

#using test data now to get AUC
test_data_aa <- read.csv(here("Natalie/data_cleaned/test_train/test_data_aa.csv"))
test_coords_aa <- test_data_aa[, c("Longitude", "Latitude")]
test_presence_aa <- as.numeric(test_data_aa$aa)
ensemble_test_pred_aa202132_h2o <- extract(ensemble_pred_aa202132_h2o, test_coords_aa, pos_label = 1)
ensemble_auc_df_aa202132_h2o <- data.frame(test_data_aa$X, test_presence_aa, ensemble_test_pred_aa202132_h2o)
auc_ensemble_aa202132_h2o<- PresenceAbsence ::auc(ensemble_auc_df_aa202132, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_aa202132_h2o, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_aa202132_h2o.csv")


#**YW202145*
aa202145_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/aa202145_glm.tif")
aa202145_h2o_glm <- raster("/Users/nooni/Box/RNR597_data/prediction/aa202145_h2o_glm.tif")
aa202145_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/aa202145_rf.tif")
aa202145_h2o_rf <- raster("/Users/nooni/Box/RNR597_data/prediction/aa202145_h2o_rf.tif")
auc_aa_202145 <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_202145.csv")
auc_aa_202145_h2o <- read.csv("C:/Users/nooni/Box/RNR597_data/AUC/auc_aa_202145_h2o.csv")

#ensemble no water
pred_stack_aa202145 <- stack(x = c(aa202145_glm, aa202145_rf))
weights_aa202145 <- auc_aa_202145$AUC / sum(auc_aa_202145$AUC)
ensemble_pred_aa202145 <- weighted.mean(pred_stack_aa202145, w = weights_aa202145)
plot(ensemble_pred_aa202145)
writeRaster(ensemble_pred_aa202145, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_aa202145.tif")

#using test data now to get AUC 
test_data_aa <- read.csv(here("Natalie/data_cleaned/test_train/test_data_aa.csv"))
test_coords_aa <- test_data_aa[, c("Longitude", "Latitude")]
test_presence_aa <- as.numeric(test_data_aa$aa)
ensemble_test_pred_aa202145 <- extract(ensemble_pred_aa202145, test_coords_aa, pos_label = 1)
ensemble_auc_df_aa202145 <- data.frame(test_data_aa$X, test_presence_aa, ensemble_test_pred_aa202145)
auc_ensemble_aa202145<- PresenceAbsence ::auc(ensemble_auc_df_aa202145, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_aa202145, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_aa202145.csv")

#h2o
pred_stack_aa202145_h2o <- stack(x = c(aa202145_h2o_glm, aa202145_h2o_rf))
weights_aa202145_h2o <- auc_aa_202145_h2o$AUC / sum(auc_aa_202145_h2o$AUC)

ensemble_pred_aa202145_h2o <- weighted.mean(pred_stack_aa202145_h2o, w = weights_aa202145_h2o)
plot(ensemble_pred_aa202145_h2o)
writeRaster(ensemble_pred_aa202145_h2o, file = "/Users/nooni/Box/RNR597_data/prediction/ensemble_pred_aa202145_h2o.tif")

#using test data now to get AUC
test_data_aa <- read.csv(here("Natalie/data_cleaned/test_train/test_data_aa.csv"))
test_coords_aa <- test_data_aa[, c("Longitude", "Latitude")]
test_presence_aa <- as.numeric(test_data_aa$aa)
ensemble_test_pred_aa202145_h2o <- extract(ensemble_pred_aa202145_h2o, test_coords_aa, pos_label = 1)
ensemble_auc_df_aa202145_h2o <- data.frame(test_data_aa$X, test_presence_aa, ensemble_test_pred_aa202145_h2o)
auc_ensemble_aa202145_h2o<- PresenceAbsence ::auc(ensemble_auc_df_aa202145, which.model = 1, na.rm = TRUE)
write.csv(auc_ensemble_aa202145_h2o, file = "C:/Users/nooni/Box/RNR597_data/AUC_ensemble/auc_ensemble_aa202145_h2o.csv")


```








